# (PART) Data Science {-} 


# This thing called "data science" {#datasciencedefined}


## Theory

David Donoho (2015) [_50 Years of Data Science_](http://courses.csail.mit.edu/18.337/2015/docs/50YearsDataScience.pdf), based on a presentation at the Tukey Centennial workshop, Princeton NJ Sept 18 2015.

* reprinted in [_Journal of Computational and Graphical Statistics_](http://amstat.tandfonline.com/toc/ucgs20/26/4?nav=tocList), Volume 26, No. 4 (2017), including a variety of discussion papers / responses, including: 

  - Jenny Bryan and Hadley Wickham, "Data	Science:	A	Three	Ring	Circus	or	a	Big	Tent?"(https://arxiv.org/ftp/arxiv/papers/1712/1712.07349.pdf) {discussion of Donoho, _50 Years of Data Science_}


Hadley Wickham (2018) [Readings in Applied Data Science](https://github.com/hadley/stats337), course materials for Standford Stats337 (spring 2018)


David Robinson (2018-01-09) ["What's the difference between data science, machine learning, and artificial intelligence?"](http://varianceexplained.org/r/ds-ml-ai/)


<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Let&#39;s try that again <a href="https://t.co/1G4wHvGvdd">pic.twitter.com/1G4wHvGvdd</a></p>&mdash; Data Science Renee (/@/BecomingDataSci) <a href="https://twitter.com/BecomingDataSci/status/773001808096661504?ref_src=twsrc%5Etfw">September 6, 2016</a></blockquote>

Mango Solutions (2018-08-15) ["Demystifying Data Science Terminology"](https://www.mango-solutions.com/blog/demystifying-data-science-terminology)


Martin Monkman (2019-06-02) ["Same name, different bird"](https://bayesball.blogspot.com/2019/06/same-name-different-bird.html) at [bayesball.blogspot.com](bayesball.blogspot.com)


## Philosophy

Angela Bassa (2017) [Data Alone Isn’t Ground Truth … and why you should always carry a healthy dose of skepticism in your back pocket](https://medium.com/@angebassa/data-alone-isnt-ground-truth-9e733079dfd4)

Tim Davies and Mark Frank (2013) [‘There’s no such thing as raw data’. Exploring the sociotechnical life of a government dataset](https://eprints.soton.ac.uk/352115/), conference paper from Web Science 2013, France (02 - 04 May 2013)

* [alternate source 1](https://dl.acm.org/citation.cfm?id=2464472)

* [alternate source 2](http://students.ecs.soton.ac.uk/mwra1g13/msc/comp6037/timed_ex_pdf/p75-davies.pdf)




## The Practice of Data Science & Statistics

Steph de Silva and John Ormerod, [The Bayesian and The Frequentist](https://www.thebayesianandthefrequentist.com/2019/03/12/to-whom-it-may-concern/) {blog}



### R Release Names

"All of the release names are references to Peanuts strips/films." 

Lucy D'Agostino McGowan, 2017-07-28, [R release names](https://livefreeordichotomize.com/2017/09/28/r-release-names/)


Releases since 2017-07-28:

* R 3.5.2 ["Eggshell Igloos"](https://www.gocomics.com/peanuts/1960/01/25) (original strip: 1960-01-25)

* R 3.5.3 ["Great Truth"](https://www.gocomics.com/peanuts/1959/03/11) (original strip: 1959-03-11)

* R 3.6.0 ["Planting of a Tree"](https://www.gocomics.com/peanuts/1963/03/03) (original strip: 1963-03-03)

(Another source for the strips is the [peanuts.fandom.com comics archive](https://peanuts.fandom.com/wiki/Category:Comic_strips))


### Using R for Data Science

Hadley Wickham & Garrett Grolemund (2016) [_R for Data Science_] [@Wickham_Grolemund2016]

Roger Peng, [_R Programming for Data Science_] [@Peng2018]

* Roger Peng's [other books on LeanPub](https://leanpub.com/u/rdpeng)

Chester Ismay and Albert Y. Kim, 2017-08-02, [An Introduction to Statistical and Data Sciences via R](http://moderndive.com/) [@Ismay_Kim_2018]

* Chester Ismay, 2017-03-02, [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)




### Using R for Data Journalism

[.Rddj: Hand-curated, high quality resources for doing data journalism with R](https://rddj.info/)

[R for Journalists](http://www.scoop.it/t/r-for-journalists) at scoop.it


### Data Science and Public Policy

[Using Big Data to Solve Economic and Social Problems](http://www.equality-of-opportunity.org/bigdatacourse/) -- course at The Equality of Opportunity Project


### Data science careers

Jonny Brooks-Bartlett (2018-03-28) [Here’s why so many data scientists are leaving their jobs](https://towardsdatascience.com/why-so-many-data-scientists-are-leaving-their-jobs-a1f0329d7ea4) -- a splash of cold water realism in the face


Nate Oostendorp (2019-03-01) ["Radical Change Is Coming To Data Science Jobs"](https://www.forbes.com/sites/forbestechcouncil/2019/03/01/radical-change-is-coming-to-data-science-jobs/#5755e19bdfcc), forbes.com


***

## The skills of data science

Of course, how you set out to learn data science hinges on how you define data science. A typology based on data users might be helpful; knowing what sort of data scientist you are will shape what you might want to learn.


### Data science leadership

Thomas H. Davenport and Jeanne G. Harris, _Competing on Analytics: The New Science of Winning_, Harvard Business School Press, January 2007. [@Davenport_Harris_2007]


* Thomas H. Davenport, ["Competing on Analytics"](https://hbr.org/2006/01/competing-on-analytics), _Harvard Business Review_, January 2006.

Angela Bassa, ["Managing a Data Science Team"](https://hbr.org/2018/10/managing-a-data-science-team), _Harvard Business Review_, 2018-10-24

[Executive Data Science](https://www.coursera.org/specializations/executive-data-science) (Coursera)

[Building a Data Science Team](https://www.coursera.org/learn/build-data-science-team) (Coursera)


### Business analytics

Sahil Arora, ["Top Data Analytics Skills Required to Become a Data Analyst"](https://www.digitalvidya.com/blog/data-analytics-skills/), Digital Vidya, 2017-03-24

Samantha Leonard, ["6 Must-Have Skills For Data Analysts"](https://www.northeastern.edu/levelblog/2018/08/31/6-must-have-skills-data-analyst/), Northeastern University, 2018-08-31




### Data science

[Data Science](https://www.coursera.org/specializations/jhu-data-science), Johns Hopkins University via Coursera

[Mango Solutions' R training](https://www.mango-solutions.com/additional-solutions/r-training) provides structure by user proficiency.


***

