# Using R 



## Introduction

In addition to there being many resources available for using R to solve statistical and data science challenges, there are also many resources on how to maximize your effectiveness using R.

This chapter compiles what I consider to be the essential texts; articles and blog posts will be at a minimum.


***

## The R community

[The R Consortium](https://www.r-consortium.org/) " is a group organized under an open source governance and foundation model to support the worldwide community of users, maintainers and developers of R software. ... The central mission of the R Consortium is to work with and provide support to the R Foundation and key organizations and groups developing, maintaining, distributing and using R software."

[The R Foundation](https://www.r-project.org/foundation/) 

>is a not for profit organization working in the public interest. It has been founded by the members of the R Development Core Team in order to
>* Provide support for the R project and other innovations in statistical computing. We believe that R has become a mature and valuable tool and we would like to ensure its continued development and the development of future innovations in software for statistical and computational research.
>* Provide a reference point for individuals, instititutions or commercial enterprises that want to support or interact with the R development community.
>* Hold and administer the copyright of R software and documentation.


Martyn Plummer, [The R Consortium and the R Foundation](https://journal.r-project.org/archive/2015-2/plummer.pdf), _The R Journal_ Vol. 7/2, December 2015


David Keyes, 2019-07-29, [If You Care About Equity, Use R](https://rfortherestofus.com/2019/07/equity/)


Julia Stewart Lowndes, 2019-12-10, [Open Software Means Kinder Science](https://blogs.scientificamerican.com/observations/open-software-means-kinder-science/), _Scientific American_ blog


***

## General & all-encompassing resources


David Smale, [Free R Reading Material](https://committedtotape.shinyapps.io/freeR/),  A Shiny app collection "of books about the R programming language and Data Science, that you can read for free!"


Jennifer Bryan and Jim Hester, [What They Forgot to Teach You About R](https://whattheyforgot.org/) -- "designed for experienced R and RStudio users who want to (re)design their R lifestyle. We focus on building holistic and project-oriented workflows that address the most common sources of friction in data analysis, _outside of doing the statistical analysis itself_."

Colin Fay, 2018-09-24, [Why do we use arrow as an assignment operator?](https://colinfay.me/r-assignment/) -- answering the second-most-asked question about R.


### Journals

[The R Journal](https://journal.r-project.org/archive/)—"the open access, refereed journal of the R project for statistical computing. It features short to medium length articles covering topics that should be of interest to users or developers of R."


[Journal of Statistical Software](https://www.jstatsoft.org/index)—not limited to R, the journal "publishes articles, book reviews, code snippets, and software reviews on the subject of statistical software and algorithms."


### Text books by subject

Jacob Kaplan (2020-01-15) [_Crime by the Numbers_](https://crimebythenumbers.com/)—"This book introduces the programming language R and is meant for undergrads or graduate students studying criminology. R is a programming language that is well-suited to the type of work frequently done in criminology - taking messy data and turning it into useful information. While R is a useful tool for many fields of study, this book focuses on the skills criminologists should know and uses crime data for the example data sets."

***

## R Release Names

The most-asked question about R? 

Answer: "All of the release names are references to Peanuts strips/films." 

Lucy D'Agostino McGowan, 2017-07-28, [R release names](https://livefreeordichotomize.com/2017/09/28/r-release-names/)


Releases since 2017-07-28:

* * R 4.0.4 ["Lost Library Book"](https://www.gocomics.com/peanuts/1972/10/23) (original strip: TBD) (R version release date: 2021-02-15)

  - Charlie Brown's lost library book was a weekday series that ran for 11 strips
  
  - The rerun of the strips started on [2006-02-27](https://www.gocomics.com/peanuts/2006/02/27), and continued through [2006-03-10](https://www.gocomics.com/peanuts/2006/03/10)


* R 4.0.3 ["Bunny-Wunnies Freak Out"](https://www.gocomics.com/peanuts/1972/10/23) (original strip: 1972-10-23) (R version release date: 2020-10-10)

  - _The Six Bunny-Wunnies Freak Out_ is detailed at the [Bunny Wunny entry at the Peanuts Wiki](https://peanuts.fandom.com/wiki/Bunny_Wunny) 


* R 4.0.2 ["Taking Off Again"](https://www.gocomics.com/peanuts/1962/04/14) (original strip: 1962-04-14) (R version release date: 2020-06-22)--two weeks after R 4.0.1 was released, R 4.0.2 was released with a few bug fixes


* R 4.0.1 ["See Things Now"](https://www.gocomics.com/peanuts/1962/02/06) (original strip: 1962-02-06) (R version release date: 2020-06-06)


* R 4.0.0 ["Arbor Day"](https://www.gocomics.com/peanuts/1970/04/24) (original strip: 1970-04-24) (R version release date: 2020-04-24)

  - The 1976 TV special [_It's Arbor Day, Charlie Brown_](https://peanuts.fandom.com/wiki/It%27s_Arbor_Day,_Charlie_Brown?fbclid=IwAR1LPS3ksgWm-MZlWZ0YicwyOCzOJK94LDfvZFibaScVrtaLY4O6ZrWzEVE) 



* R 3.6.3 ["Holding the Windsock"](https://www.gocomics.com/peanuts/2000/02/29) (original strip: 2000-02-29—this date also saw the release of R 1.0.0!) (R version release date: 2020-02-29)

  - Peter Dalgaard's [original announcement of the release of R-1.0.0 to stat.ethz.ch](https://stat.ethz.ch/pipermail/r-announce/2000/000127.html)


* R 3.6.2 ["Dark and Stormy Night"](https://www.gocomics.com/peanuts/1965/07/12) (original strip: 1965-07-12) (R version release date: 2019-12-12)

  - the first appearance was the beginning of a running storyline that ran for the five subsequent strips (through 1965-07-17)

  - it is a recurring theme in Snoopy's writings; Lucy points this out in the strip from [1997-04-12](https://www.gocomics.com/peanuts/1997/04/22)

  - a complete story was published in 1971 as _Snoopy and the Dark and Stormy Night_ (Holt, Rinehart & Winston); [summary here](http://curiouspages.blogspot.com/2010/02/snoopy-and-it-was-dark-and-stormy-night.html); [full text here](https://mikeconley.ca/blog/2010/02/13/it-was-a-dark-and-stormy-night/) 

  - an in-depth assessment of Snoopy's use of "It was a dark and stormy night" can be found at tvtropes, under ["It Was a Dark and Stormy Night"](https://tvtropes.org/pmwiki/pmwiki.php/Main/ItWasADarkAndStormyNight); see the "Newspaper Comics" folder
  
  - The literary cliche ["It was a dark and stormy night" has its own wikipedia entry](https://en.wikipedia.org/wiki/It_was_a_dark_and_stormy_night)


* R 3.6.1 ["Action of the Toes"](https://www.gocomics.com/peanuts/1971/03/22) (original strip: 1971-03-22) (R version release date: 2019-07-05)

* R 3.6.0 ["Planting of a Tree"](https://www.gocomics.com/peanuts/1963/03/03) (original strip: 1963-03-03) (R version release date: 2019-04-26)

* R 3.5.3 ["Great Truth"](https://www.gocomics.com/peanuts/1959/03/11) (original strip: 1959-03-11) (R version release date: 2019-03-11)

* R 3.5.2 ["Eggshell Igloos"](https://www.gocomics.com/peanuts/1960/01/25) (original strip: 1960-01-25) (R version release date: 2018-12-20)



(Another source for the strips is the [peanuts.fandom.com comics archive](https://peanuts.fandom.com/wiki/Category:Comic_strips))


***


## R Introductions

Nathaniel D. Phillips, [YaRrr! The Pirate’s Guide to R](https://bookdown.org/ndphillips/YaRrr/)


***

## The R toolbox

### CRAN

[The Comprehensive R Archive Network](https://cran.r-project.org/) -- CRAN for short -- "is a network of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R." This is the place to get your installation of R, and the production versions of your favourite packages.

### RStudio -- the IDE

"RStudio" can mean one of two things:

* [the integrated development environment (IDE) for R](https://www.rstudio.com/products/rstudio/)

* [the company](https://www.rstudio.com/) which makes the IDE, as well as enterprise software and a variety of packages

### Packages

Antoine Bichat's [favoriteRpackages](https://github.com/abichat/favoriteRpackages)



***


## R as a programming environment

Colin Gillespie and Robin Lovelace, _Efficient R Programming_ [@Gillespie_Lovelace_2017]

Hadley Wickham, _Advanced R_ [@Wickham_advancedR]

Hadley Wickham, _R Packages_ [@Wickham_R-packages]


### Debugging R

Hadley Wickham, ["Debugging"](https://adv-r.hadley.nz/debugging.html), Chapter 22 in _Advanced R_ [@Wickham_advancedR]

Jonathan McPherson, 2019-05-20, [Debugging with RStudio](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio)

Jennifer Bryan and Jim Hester, ["Debugging R code"](https://whattheyforgot.org/debugging-r-code.html), Chapter 11 in _What They Forgot to Teach You About R_

Jenny Bryan (2020-01-30) [Object of type 'closure' is not subsettable](https://github.com/jennybc/debugging#readme)—talk at rstudio::conf 2020 


### R as part of the Data Science Toolbox

Jessica Minnier, 2019-07-29, [Sharpening the Tools in Your Data Science Toolbox](https://jminnier-talks.netlify.com/2019_07_jsm_datascienceskills/2019_07_jsm_datascience#1)


### The R-Python interface


#### `{feather}`

{feather} is designed to read and write feather files, a lightweight binary columnar data store designed for maximum speed. There is a [parallel Python package](https://github.com/wesm/feather).


* CRAN: [feather: R Bindings to the Feather 'API'](https://cran.r-project.org/web/packages/feather/index.html)

* Hadley Wickham, 2016-03-29, [Feather: A Fast On-Disk Format for Data Frames for R and Python, powered by Apache Arrow](https://blog.rstudio.com/2016/03/29/feather/)



#### `{reticulate}`

The reticulate package provides a comprehensive set of tools for interoperability between Python and R.

* [R Interface to Python](https://rstudio.github.io/reticulate/)

* JJ Allaire, 2018-03-26, [reticulate: R interface to Python](https://blog.rstudio.com/2018/03/26/reticulate-r-interface-to-python/)

* Jo Hardin, 2019-07-16, [reticulate: running Python within RStudio](https://teachdatascience.com/reticulate/) at teachdatascience.com 


* [{reticulate} cheat sheet](https://resources.rstudio.com/rstudio-developed/reticulate)



#### `{rpy2}`


JD Long, twitter thread on {rpy2} documentation: [twitter thread](https://twitter.com/CMastication/status/1157645891672707072?s=20)







-30-
