# Data Sources and How to Access Them {#datasources}



## Introduction


What is data science without _data_?  Here's a few indexes and compendiums of data sources, including R packages that conveniently either bundle those data or provide mechanisms to access data from remote sources.

* Kim, A. Y, Ismay, C., & Chunn, J. (2018). The fivethirtyeight R Package: "Tame Data" Principles for Introductory Statistics and Data Science Courses. _Technology Innovations in Statistics Education_, 11(1). Retrieved from https://escholarship.org/uc/item/0rx1231m

## Sources

### listings

University of Alberta Libraries, Economics: [List of databases](http://guides.library.ualberta.ca/c.php?g=329741&p=2334221)

Simon Fraser University Library: [Gender, Sexuality & Women's Studies Information Resources: Facts & Data](http://www.lib.sfu.ca/help/research-assistance/subject/gsws/factsdata)

### open data sources

[United Nations Population Prospects](https://esa.un.org/unpd/wpp/) - detailed country population data 

* [populationpyramid.net](https://www.populationpyramid.net/) uses this data

[OECD world data, by country](https://data.oecd.org/)

[Gapminder](https://www.gapminder.org/data/) - all indicators displayed in Gapminder World


<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Anyone know of a good migration dataset? Ideally # of people moving from country i to country j by year</p>&mdash; Savage Jim (/@/jim_savage_) <a href="https://twitter.com/jim_savage_/status/1094672164928802816?ref_src=twsrc%5Etfw">February 10, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>



## R packages


### **cancensus**

[Census of Canada (including the National Household Survey)](https://github.com/mountainMath/cancensus)



### **cansim**

**package**

[github](https://github.com/mountainMath/cansim)

**articles**

Dmitry Shkolnik (2018-08-01) [The CANSIM package, Canadian tourism, and slopegraphs](https://www.dshkol.com/2018/cansim-package-tourism-slopegraphs/)


### **CANSIM2R**

[CANSIM2R: Directly Extracts Complete CANSIM Data Tables](https://cran.r-project.org/package=CANSIM2R)

github: [CANSIM2R](https://github.com/MarcoLugo/CANSIM2R)

* Andrew Clarke (2017-08-09) [StatCan API's Discovered](https://www.mytinyshinys.com/2017/08/09/statcanapi/)


### **gapminder**

[gapminder: Data from Gapminder](https://cran.r-project.org/package=gapminder) An excerpt of the data available at [Gapminder.org]. For each of 142 countries, the package provides values for life expectancy, GDP per capita, and population, every five years, from 1952 to 2007. 


### **Lahman**

[Lahman: Sean 'Lahman' Baseball Database](https://cran.r-project.org/package=Lahman/)  Provides the tables from the 'Sean Lahman Baseball Database' as a set of R data.frames. It uses the data on pitching, hitting and fielding performance and other tables from 1871 through 2015, as recorded in the 2016 version of the database.



