# Data Wrangling (emphasis on tidy data) {#datawrangling}

> If 80% of the data scientist's job is data cleaning, perhaps that _is_ the job. (Source: Anon.)


## Introduction

Data is rarely in condition to use it...there's invariably something amiss.  Data wrangling (a.k.a. data carpentry) is the process of getting it ready for analysis.

And all too often, data are messy. There are rows with no contents, colour-coded cells, and inconsistent values.

One important way that data can be cleaned is to ensure that the structure is tidy. What do we mean by tidy data?

> There are three interrelated rules which make a dataset tidy:
> * Each variable must have its own column.
> * Each observation must have its own row.
> * Each value must have its own cell.

And 

> Why ensure that your data is tidy? There are two main advantages:
> 
> 1. There’s a general advantage to picking one consistent way of storing data. If you have a consistent data structure, it’s easier to learn the tools that work with it because they have an underlying uniformity.
>
> 2. There’s a specific advantage to placing variables in columns because it allows R’s vectorised nature to shine. As you learned in mutate and summary functions, most built-in R functions work with vectors of values. That makes transforming tidy data feel particularly natural.

(from [@Wickham_Grolemund2016])


This won't solve things like inconsistent values and colour-coded cells, but it will solve some other messiness.

For more about the principles of tidy data, see Hadley Wickham's article "Tidy data", in _The Journal of Statistical Software_ [@tidydata]

  + [alternate link:](http://vita.had.co.nz/papers/tidy-data.html)
  + [informal and code-heavy version](https://cran.r-project.org/package=tidyr/vignettes/tidy-data.html)
 

### Other tidyverse references

Karl Broman and Kara Woo, ["Data organization in spreadsheets"](https://github.com/kbroman/Paper_DataOrg) (github page with source manuscript) -- application of tidy principles to spreadsheets.

* see also Karl Broman's tutorial, ["Data organization: organizing data in spreadsheets)


Bruno Rodriguez, [Modern R with the tidyverse](https://b-rodrigues.github.io/modern_R/)


Jesse Sadler, [Excel vs R: A Brief Introduction to R  (With examples using dplyr and ggplot](http://kbroman.org/dataorg/](https://www.jessesadler.com/post/excel-vs-r/) (2017-10-02)




## Theory and methods


[Stat 545: Data wrangling, exploration, and analysis with R](http://stat545.com/index.html) -- course materials associated with the University of British Columbia's Statistics 545 course. Prepared in large part by Dr. Jenny Bryan.


### Joins

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">the steps in a left join <a href="https://t.co/YSFAdxFl1D">pic.twitter.com/YSFAdxFl1D</a></p>&mdash; 🔎Julia Evans🔍 (@b0rk) <a href="https://twitter.com/b0rk/status/1184601536413999104?ref_src=twsrc%5Etfw">October 16, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


***

## Tools


### `{datapasta}`

Vignette: [How to Datapasta](https://cran.r-project.org/web/packages/datapasta/vignettes/how-to-datapasta.html)



### `{janitor}`



### `{vtable}`

CRAN page: [vtable: Variable Table](https://cran.r-project.org/web/packages/vtable/index.html) -- Automatically generates HTML variable documentation including variable names, labels, classes, value labels (if applicable), value ranges, and summary statistics.

[Reference page](http://nickchk.com/vtable.html)

Twitter thread by Nick Huntington-Klein, [2019-03-24](https://threadreaderapp.com/thread/1109917303947223040.html)



***

## The tidyverse

[The tidyverse: ](http://tidyverse.org/)

[The tidyverse R packages on github](https://github.com/hadley/tidyverse)


### `{dplyr}`

**package**

CRAN: [dplyr: A Grammar of Data Manipulation](https://CRAN.R-project.org/package=dplyr)

github: [hadley/dplyr](https://github.com/hadley/dplyr)

**articles**

* [Introduction to **dplyr**](http://stat545.com/block009_dplyr-intro.html), part of the UBC [STAT545: Data wrangling, exploration, and analysis with R](http://stat545.com/index.html) course materials


* Gary Hutson, 2018-05-24, [**DPLYR**: A Beginners Guide](https://www.r-bloggers.com/dplyr-a-beginners-guide/)


Isabella R. Ghement, 2019-07-18, [`group_split()` function](https://threadreaderapp.com/thread/1151579390771224576.html) -- twitter thread with a short example

Francois Romain, 2019-07-10, [n() cool #dplyr things](https://speakerdeck.com/romainfrancois/n-cool-number-dplyr-things), presentation at UseR2019, Toulouse

Garrick Aden-Buie, [Tidy Animated Verbs](https://www.garrickadenbuie.com/project/tidyexplain/) -- "Animations of tidyverse verbs using R, the tidyverse, and gganimate." Good visual demonstrations the various types of joins. 

* GitHub repo for [tidyexplain](https://github.com/gadenbuie/tidyexplain)


[SQL Joins Explained](https://www.sql-join.com/)



### `{forcats}`

[reference page](https://forcats.tidyverse.org/)

Working with factors

[Be the boss of your factors](https://stat545.com/block029_factors.html#change-order-of-the-levels-because-i-said-so)


Emily Robinson, _Categorical data in the tidyverse_ {link to DataCamp course removed}



### `{purrr}`


[reference page](https://purrr.tidyverse.org/)

CRAN: [purrr: Functional Programming Tools](https://cran.r-project.org/package=purrr)


**tutorials**

Jenny Bryan, [purrr tutorial](https://jennybc.github.io/purrr-tutorial/index.html)

- including a section on the remarkable [list columns](https://jennybc.github.io/purrr-tutorial/ls13_list-columns.html), i.e. a column within a dataframe that contains a general vector, that is a list of values, as opposed to an atomic vector.

- and here's the related ["Putting square pegs in round holes: using list-cols in your dataframe"](https://speakerdeck.com/jennybc/putting-square-pegs-in-round-holes-using-list-cols-in-your-dataframe)

["Iteration"](https://r4ds.had.co.nz/iteration.html) in _R for Data Science_ [@Wickham_Grolemund2016]

Emorie D Beck, [Intro to purrr](https://emoriebeck.github.io/R-tutorials/purrr/)

Sharon Machlis, [R Tip: Access nested list items with purrr](https://www.infoworld.com/video/90327/r-tip-access-nested-list-items-with-purrr) {video}


[A purrr tutorial](https://github.com/Cascadia-R/purrr-tutorial) -- Cascadia-R, 2017-06-03

Charlotte Wickham, [purr tutorial](https://github.com/cwickham/purrr-tutorial) -- github



***

### more about tidy data

* Hadley Wickham & Garrett Grolemund, [_R for Data Science_](http://r4ds.had.co.nz/)

* Hadley Wickham
  + [Tidy data and tidy tools (video of presentation, December 2011)](https://vimeo.com/33727555)

* Garrett Grolemund
  + [Data Tidying](http://garrettgman.github.io/tidying/) (part of [Data Science with R](http://garrettgman.github.io/))
  
* Chester Ismay and Ted Laderas, [A gRadual-intRoduction to the tidyverse](https://github.com/Cascadia-R/gRadual-intRoduction-tidyverse?utm_content=buffer98896&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)  




## Working with dates

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Updated Turing Test concept:<br>A spreadsheet of dates, hand-entered by interns more than a decade ago, featuring such well-known time formats as &quot;1996ish&quot;, &quot;1941/xd01944&quot;, &quot;1955?&quot; and &quot;WWII.&quot;<br>I&#39;m not worried about AI until someone shows me the algorithm that can make sense of this. <a href="https://t.co/IhzofigX2b">pic.twitter.com/IhzofigX2b</a></p>&mdash; Brooke Watson (/@/brookLYNevery1) <a href="https://twitter.com/brookLYNevery1/status/954368989181902848?ref_src=twsrc%5Etfw">January 19, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


### `{lubridate}`

[Do more with dates and times in R](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html)


[tidyverse page](https://lubridate.tidyverse.org/)



### `{anytime}`

[{anytime}: Convert Any Input to Parsed Date or Datetime](http://dirk.eddelbuettel.com/code/anytime.html) -- vignette

  
### Tidy evaluation

* programming with {dplyr}

Edwin Thoen, 2017-08-25 [Tidy evaluation, most common actions](https://edwinth.github.io/blog/dplyr-recipes/)



### Tidy text

If  you're going to undertake text mining and natural language processing, your text (i.e. your data) needs to be tidy.  Fortunately, there's an R package for that: `tidytext`.

See the companion chapter on the topics of [Text Analysis and Text Mining].



-30-
