# How to Read Data {#dataread}


You've got some data, now you need to get it into your R environment.



## Introduction



## Labelled data

In particular, survey data

* Marta Kołczyńska, 2019-03-03, [Searchable codebook from labelled data in R](https://martakolczynska.com/post/codebook-labelled-data/)


## R readers

**articles**

[R database interfaces](http://www.burns-stat.com/r-database-interfaces/)


### `{rio}`

**package**

CRAN page: _currently only development version_, see tidyverse link below 

vignette: [Import, Export, and Convert Data Files](https://cran.r-project.org/package=rio/vignettes/rio.html)



### `{googledrive}`

**package**

CRAN page: _currently only development version_, see tidyverse link below 

tidyverse page: [`googledrive`](https://tidyverse.github.io/googledrive/)



### `{foreign}`

**package**

CRAN page: [foreign: Read Data Stored by Minitab, S, SAS, SPSS, Stata, Systat, Weka, dBase, ...]( https://CRAN.R-project.org/package=foreign)

**articles**

* [How to open an SPSS file into R](http://www.milanor.net/blog/how-to-open-an-spss-file-into-r/), by Davide Massidda (2014-03-26)


### `{haven}` 

**package**

**articles**


## PDF files

Luis D. Verde, 2018-12-14, [Tidyeval meets PDF table hell](http://luisdva.github.io/rstats/Tidyeval-pdf-hell/) -- great solution to the common problem of broken rows ("values that are broken up into two lines for whatever reason (often to optimize space on a page in a table in a typeset pdf)"). 




## Stata files

### `{read.dta}`

Reads a file in Stata version 5–12 binary format into a data frame.

CRAN page: [`read.dta`: Read Stata Binary Files](http://stat.ethz.ch/R-manual/R-devel/library/foreign/html/read.dta.html)


### `{readstata13}`

Function to read and write the 'Stata' file format.

CRAN Page: [readstata13: Import 'Stata' Data Files](readstata13: Import 'Stata' Data Files)



## Time series database files

### `{TSdbi}` and related packages

**package**

CRAN page: [TSdbi: Time Series Database Interface]( https://CRAN.R-project.org/package=TSdbi)

Note: {TSdbi} has some related extension packages:

* CRAN page: [TSdata: 'TSdbi' Illustration](https://cran.r-project.org/package=TSdata)
*  This package gives an overview and usage examples for all the `TSdbi` family of packages

* CRAN page: [TSPostgreSQL: 'TSdbi' Extensions for 'PostgreSQL'](https://cran.r-project.org/package=TSPostgreSQL)

* CRAN page: [TSsdmx: 'TSdbi' Extension to Connect with 'SDMX'](https://cran.r-project.org/package=TSsdmx)


-30-