# (PART) Data Visualization {-} 


# General {#datavisualization}


## Introduction

This is an _enormous_ topic. 

But start here: 

* Alberto Cairo, _The Functional Art_ [@Cairo_2013] and _The Truthful Art_ [@Cairo_2016] are framed in the context of Cairo's professional expertise in "data journalism".

  -- Cairo's blog has a number of very good posts, including:
  
  -- [Keep those legends ](http://www.thefunctionalart.com/2019/07/keep-those-legends.html) (2019-07-17)
  

* William S. Cleveland's books, _Visualizing Data_ [@Cleveland_1993] and _The Elements of Graphing Data_ [@Cleveland_1994], are classics in the field of statistical graphics.

* Kennedy Elliot, [Everything we know about how humans interpret graphics](https://www.youtube.com/watch?v=s0J6EDvlN30), video of talk given at OpenVis conference, 2016-04-25 & 26.

* Jill H. Larkin and Herbert A. Simon, "Why a diagram is (sometimes) worth ten thousand words", _Cognitive Science_, 1987 [@Larkin_Simon_1987]

* Elijah Meeks, ["What Charts Do"](https://medium.com/@Elijah_Meeks/what-charts-do-48ed96f70a74) (2018-05-21) is a succinct summary that's worth reading.

* Cole Nussbaumer Knaflic, _Storytelling with Data_ [@NussbaumerKnaflic_2015]. A great introduction to the fundamentals of good visualization. The [companion blog](https://www.storytellingwithdata.com/) has an on-going series of further dives into the topic.

* Naomi Robbins, _Creating More Effective Graphs_. [@Robbins_2013]

* Alan Smith, ["Data visualisation: it is not all about technology"](https://www.ft.com/content/aba6c58e-5a8e-11e7-9bc8-8055f264aa8b?accessToken=zwAAAVz0i_FYkdOrpsWOWo4R59ObyIBV8mSqiw.MEQCIFBdm394GSC6W-YIMME93SN8BgAuLEfyK8nFshbAiyu-AiBx6Qx4Ivd3qh-VSfIlwrf5tYKdnbGId1n0pzxZFUwDsQ&sharetype=gift), _Financial Times_, 2017-06-28

* John W. Tukey, _Exploratory Data Analysis_ [@Tukey_1977] is a classic--it might seem dated with its heavy reliance on analogue methods (for example, the suggestions about graph paper (p.127)), but the concepts are timeless.



## General resources

* F.J. Anscombe, "Graphs in Statistical Analysis" -- the classic paper that introduced the justifiably-famous [_Anscombe's Quartet_](https://en.wikipedia.org/wiki/Anscombe%27s_quartet) [@Anscombe_1973]

* [Enrico Bertini's homepage](http://enrico.bertini.io/) -- a plethora of articles and resources on data visualization

* [Data Visualization Inventors, Founders, and Developers](https://policyviz.com/2019/01/09/data-visualization-inventors-founders-and-developers/) -- credit where credit is due

* Richard Brath & Ebad Banissi, 2016, ["Using Typography to Expand the
Design Space of Data Visualization"](https://www.sciencedirect.com/science/article/pii/S2405872616300107), _She Ji: The Journal of Design, Economics, and Innovation_, Vol. 2, Issue 1, Spring 2016

* Karl Broman, [The top ten worst graphs](https://www.biostat.wisc.edu/~kbroman/topten_worstgraphs/)

* William Cleveland & Robert McGill, "Graphical Perception: Theory, Experimentation, and Application to the Development of Graphical Methods" [@Cleveland_and_McGill_1984]

* Keith Collins (2015-12-23), [The most misleading charts of 2015, fixed](https://qz.com/580859/the-most-misleading-charts-of-2015-fixed/); good discussion of problematic choices with axis scales.


* [Financial Times Visual Vocabulary](https://github.com/ft-interactive/chart-doctor/tree/master/visual-vocabulary), "A poster (available in English, Japanese, traditional Chinese and simplified Chinese) and web site to assist designers and journalists to select the optimal symbology for data visualisations, by the Financial Times Visual Journalism Team."



* Steve Franconeri, [Chart Chooser](http://experception.net/)

    - background: ["Multiple views on how to choose a visualization"](https://medium.com/multiple-views-visualization-research-explained/multiple-views-on-how-to-choose-a-visualization-b3ffc99fcddc), 2019-04-24, at medium.com


* Michael Friendly, [DataVis.ca](http://datavis.ca/) -- a variety of resources, including the "Milestones Project" (significant events in the history of data visualization), books, courses, papers, and R materials.


* Kieran Healy _Data Visualization: A practical introduction_. [@Healy_2019]
    
    - [online version](http://socviz.co/)



* Kate Moran, 2017-08-06, ["How to Present Scientific Findings Online"](https://www.nngroup.com/articles/scientific-findings-online/) (file under: Know Your Audience)

* Tamara Munzer, [list and links to talks](http://www.cs.ubc.ca/~tmm/talks.html?utm_content=bufferd5cd8&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#cj16)

* PolicyViz, [DataViz Cheatsheet](https://policyviz.com/2018/08/07/dataviz-cheatsheet/) (2018-08-07)


* Rougier NP, Droettboom M, Bourne PE (2014) "Ten Simple Rules for Better Figures".  [@Rougier_etal_2014]


* Howard Wainer, "How to Display data Badly" [@Wainer_1984]

* Claus O. Wilke (2019, full draft) [_Fundamentals of Data Visualization_](http://serialmentor.com/dataviz/)

  - Important: Wilke notes that this is a platform-agnostic book, but it was written in R's {bookdown} and uses {ggplot2} for all of the figures.

  - [the github repo for the book](https://github.com/clauswilke/dataviz) (in case you want to plagiarize the code for a specific figure)


* Google, [_Data Visualization_](https://material.io/design/communication/data-visualization.html#), part of Google's [Material](https://material.io/)

  - Mark Wilson, 2019-06-28, ["Google’s six rules for great data design"](https://www.fastcompany.com/90369607/googles-six-rules-for-great-data-design) (at FastCompany)


### Data Visualization Society (Medium)

Medium's [Data Visualization Society](https://medium.com/data-visualization-society) "Data Visualization Society aims to collect and establish best practices, fostering a community that supports members as they grow and develop data visualization skills."


* Allen Hillery, 2019-05-06, [W.E.B Du Bois and Four Essential Steps to Effective Persuasion](https://medium.com/data-visualization-society/w-e-b-dubois-and-four-essential-steps-to-effective-persuasion-6108a70a5708?sk=467b19142f3bec315582ac4f100d9db6)


* Michael Correll (2018-11-20) [What Does “Visualization Literacy” Mean, Anyway?](https://medium.com/multiple-views-visualization-research-explained/what-does-visualization-literacy-mean-anyway-22f3b3badc0) 


* Kennedy Elliot (2016-05-02) [39 studies about human perception in 30 minutes](https://medium.com/@kennelliott/39-studies-about-human-perception-in-30-minutes-4728f9e31a73)



***

## R Resources

### general

* [R Graph Catalog](http://shiny.stat.ubc.ca/r-graph-catalog/) -- an unbeatable resource for making good graphs in R, described by the creators as "a complement to _Creating More Effective Graphs_ by Naomi Robbins."  [@Robbins_2013]

* Michael Friendly and David Meyer (2016) _Discrete Data Analysis with R_ [@Friendly_Meyer_2016]

* Kieran Healy _Data Visualization: A practical introduction_. [@Healy_2019]
    
    - [online version](http://socviz.co/)


* [Shiny apps for statistics](https://statistics.calpoly.edu/shiny) -- by the Statistics Department at CalPoly



## {ggplot2] -- the pre-eminent way to create charts and graphs in R

* [{ggplot2}: part of the tidyverse](http://ggplot2.tidyverse.org/index.html) -- reference materials, examples, etc etc. Start here.

* [Top 50 {ggplot2} Visualizations - The Master List (With Full R Code)](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)

* [A Compendium of Clean Graphs in R](http://shinyapps.org/apps/RGraphCompendium/index.php), by Eric-Jan Wagenmakers and Quentin F. Gronau

* [BBC Visual and Data Journalism cookbook for R graphics](https://bbc.github.io/rcookbook/)

   - [{bbplot}](https://github.com/bbc/bbplot), a package with their templates etc.
   
   - ["How the BBC Visual and Data Journalism team works with graphics in R"](https://medium.com/bbc-visual-and-data-journalism/how-the-bbc-visual-and-data-journalism-team-works-with-graphics-in-r-ed0b35693535)


* Gina Reynolds, 2019-01-31, [the ggplot flipbook](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#1)

* Will Chase, 2019-05-29, [R you ready to make charts?](https://www.williamrchase.com/slides/ggplot_intro.html#64), Philly dataviz meetup

* Dana Paige Seidel, [Default ggplot2 aesthetics by geom](https://gist.github.com/dpseidel/57f28ccc034ccfdd0cf25b6c6c82a635)


### extensions

There are many extension packages that allow you to make other visualizations in {ggplot2}. Some are catalogued at [www.ggplot2-exts.org](https://www.ggplot2-exts.org/index.html).

* Gallery of {ggplot2} extensions: [ggplot2-exts.org/gallery/]({ggplot2} extensions - gallery )

#### {ggfittext}

"ggplot2 geoms to fit text into boxes"

* GitHub page: [wilkox/ggfittext](https://github.com/wilkox/ggfittext)

* Reference page: [ggfittext](https://wilkox.org/ggfittext/)



### tips and tricks

* Simon Jackson, 2016-08-11, [Plotting background data for groups with {ggplot2}](https://drsimonj.svbtle.com/plotting-background-data-for-groups-with-ggplot2)

* Laura Ellis, 2018-08-01, [Highlighting with {ggplot2}: The Old School and New School Way](https://www.littlemissdata.com/blog/highlight)


* Sharon Machlis, 2019-07-24, [How to write your own ggplot2 functions in R](https://www.infoworld.com/article/3410295/how-to-write-your-own-ggplot2-functions-in-r.html)

** _Note:_**



### Plotly

Plotly for R allows you to "Create interactive, D3 and WebGL charts in R" (their words, not mine). A great resource for upping the content of online visualizations.

* Carson Sievert, [_Plotly for R_](http://plotly-book.cpsievert.me/)


***

## Colour

Colour is a vital part of good data visualization; the following links support the use of colour in R.


* [R color cheatsheet](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf)


### {colorspace}

"A Toolbox for Manipulating and Assessing Colors and Palettes"

* [{colorspace} homepage](http://colorspace.r-forge.r-project.org/)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Looking forward to my <a href="https://twitter.com/UseR2019_Conf?ref_src=twsrc%5Etfw">@UseR2019_Conf</a> presentation about color palettes with <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> pkg <a href="https://twitter.com/hashtag/colorspace?src=hash&amp;ref_src=twsrc%5Etfw">#colorspace</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://twitter.com/hashtag/useR2019?src=hash&amp;ref_src=twsrc%5Etfw">#useR2019</a> <a href="https://twitter.com/hashtag/endrainbow?src=hash&amp;ref_src=twsrc%5Etfw">#endrainbow</a><br><br>When: 14:00<br>Where: Saint-Exupéry<br><br>Web: <a href="https://t.co/pdjmkYiDkV">https://t.co/pdjmkYiDkV</a><br>Interactive apps: <a href="https://t.co/YFC7gjKCKT">https://t.co/YFC7gjKCKT</a><br>Slides: <a href="https://t.co/KOiC1NmrMF">https://t.co/KOiC1NmrMF</a> <a href="https://t.co/cPF9ZF8Cl1">pic.twitter.com/cPF9ZF8Cl1</a></p>&mdash; Achim Zeileis (@AchimZeileis) <a href="https://twitter.com/AchimZeileis/status/1149239509751672832?ref_src=twsrc%5Etfw">July 11, 2019</a></blockquote>



### ColorBrewer

The ColorBrewer palettes were designed by Dr. Cythia Brewer  -- a variety of palettes designed for data visualization (including maps)

[ColorBrewer 2.0](http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) -- tool for selecting colour schemes (centred on maps, but they work just as well for other forms of data visualization)

Cynthia A. Brewer (2003). A Transition in Improving Maps: The ColorBrewer Example. Cartography and Geographic Information Science [@Brewer_2003] 

Cynthia A. Brewer, Geoffrey W. Hatchard, and Mark A. Harrower (2003) ColorBrewer in Print: A Catalog of Color Schemes for Maps, Cartography and Geographic Information Science [@Brewer_etal_2003].




#### the R package [{RColorBrewer}]()

* [RColorBrewer's Palettes](https://www.r-graph-gallery.com/38-rcolorbrewers-palettes/) from The R Graph Gallery

* Stewart MacArthur, 2010-12-08, ["R: Using RColorBrewer to colour your figures in R"](https://www.r-bloggers.com/r-using-rcolorbrewer-to-colour-your-figures-in-r/)



### other colour notes and guides

* Tom Jager (2018-06-25) [How to Optimize Charts For Color Blind Readers Using Color Blind Friendly Palettes](https://venngage.com/blog/color-blind-friendly-palette/)

* Alberto Cairo, 2019-06-26, ["Our understanding of rainbow colour schemes remains incomplete"](http://www.thefunctionalart.com/2019/06/our-understanding-of-rainbow-color.html)

* Robert Simmon, ["Use of Color in Data Visualization"](https://earthobservatory.nasa.gov/resources/blogs/intro_to_color_for_visualization.pdf) {pdf}

* Alan Wilson, 2017-02-27, ["The Power of The Palette: Why Color is Key in Data Visualization and How to Use It"](https://theblog.adobe.com/the-power-of-the-palette-why-color-is-key-in-data-visualization-and-how-to-use-it/) at Adobe Blog




### palettes in R

* Clay Ford, 2016-06-10, ["Setting up Color Palettes in R"](https://data.library.virginia.edu/setting-up-color-palettes-in-r/)


* [R color cheatsheet](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf)



-30-


