# (PART) Quantitative methods {-} 


# Introduction {#quantitativemethods1}


## Statistics and other quantitative methods: courses and text books

### Statistics in R

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">R advice needed - I am (thinking of) switching my undergrad &#39;metrics class from Stata to R.  2 questions: 1 - what exactly do my students (and I!) need to download to use R  2 - what introductory tutorial is most helpful for students (and me)</p>&mdash; Amanda Agan (/@/amandayagan) <a href="https://twitter.com/amandayagan/status/1078392069503229958?ref_src=twsrc%5Etfw">December 27, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


Andrew Bruce and Peter Bruce, [Practical Statistics for Data Scientists](https://www.oreilly.com/library/view/practical-statistics-for/9781491952955/)


Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer, [Introduction to Econometrics with R](https://www.econometrics-with-r.org/index.html)

Chester Ismay and Albert Y. Kim, [An Introduction to Statistical and Data Sciences via R](https://moderndive.com/index.html)

Danielle Navarro, [Learning Statistics with R](https://learningstatisticswithr.com/)

Danielle Navarro, [Learning Statistics with R: A tutorial for psychology students and other beginners](https://open.umn.edu/opentextbooks/textbooks/learning-statistics-with-r-a-tutorial-for-psychology-students-and-other-beginners)


### Statistics: general and other tools

Minitab Express Support, [Help and How-To](https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/help-and-how-to/)

* essentially an introduction to descriptive and inferential statistics




***

## Distributions



### Beta distribution

[What is the intuition behind beta distribtution? (CrossValidated)](http://stats.stackexchange.com/questions/47771/what-is-the-intuition-behind-beta-distribution)


### R

#### `{distributions3}`

"Tools to create and manipulate probability distributions using S3. Generics random(), pdf(), cdf() and quantile() provide replacements for base R's r/d/p/q style functions. Functions and arguments have been named carefully to minimize confusion for students in intro stats courses. The documentation for each distribution contains detailed mathematical notes."

* CRAN: [distributions3: Probability Distributions as S3 Objects](https://cran.r-project.org/package=distributions3/)

* Alex Hayes, [Announcing the distributions3 package](https://www.alexpghayes.com/blog/announcing-the-distributions3-package/)


***

## Randomization and random number generation


### Introduction

Randomization and random number generation has a variety of applications in data science, from creating mock or test data to pulling survey samples from lists.


### Theory and methods



### R

Martin Monkman, 2013-12-01, ["A few random things"](http://bayesball.blogspot.ca/2013/12/a-few-random-things.html)

[correlated random variables: a gist](https://gist.github.com/MonkmanMH/a8b58f9cb140d702139b75467806c6d1)


#### Random() `{base R}`

**package**

CRAN page: [Random {base}: Random number generation](http://stat.ethz.ch/R-manual/R-devel/library/base/html/Random.html)



#### `{random}`

**package**

CRAN page: [random: True Random Numbers using RANDOM.ORG](https://cran.r-project.org/package=random/)


#### `{sampling}`

**package**

CRAN page: [sampling: Survey Sampling](https://cran.r-project.org/package=sampling)

**articles**

Examples of how the package can be applied



-30-
