# Bayesian Methods {#bayesian}




### Theory and methods

[Bayesian statistics: Wikipedia page](https://en.wikipedia.org/wiki/Bayesian_statistics)

Andrew Gelman et al., _Bayesian Data Analysis_ (third edition) [@Gelman_etal_2014].

Robert Grant (2018-08-07) [How (not) to introduce newcomers to Bayesian analysis](https://robertgrantstats.wordpress.com/2018/08/07/how-not-to-introduce-newcomers-to-bayesian-analysis/)


#### R-based

Richard McElreath, 2016, _Statistical Rethinking: A Bayesian Course with Examples in R and Stan_ [@McElreath_2016].

* [`rethinking`](https://github.com/rmcelreath/rethinking), the companion R package

* [McElreath's YouTube channel](https://www.youtube.com/channel/UCNJK6_DZvcMqNSzQdEkzvzA), with Statistical Rethinking lectures



Jim Albert, _Bayesian Computation with R_ [@Albert_2009]


David Robinson, [_Introduction to Empirical Bayes_](https://gumroad.com/l/empirical-bayes)

* [github page](https://github.com/dgrtwo/empirical-bayes-book/blob/master/beta-distribution.Rmd)

* [book announcement](http://varianceexplained.org/r/empirical-bayes-book/) (2017-12-27)

* based on 10 blog posts: the final post has a listing of the previous 9 
["Simulation of empirical Bayesian methods (using baseball statistics)"](http://varianceexplained.org/r/simulation-bayes-baseball/)

Daniel Lüdecke, 2018-06-06, [R functions for Bayesian Model Statistics and Summaries](https://strengejacke.wordpress.com/2018/06/06/r-functions-for-bayesian-model-statistics-and-summaries-rstats-stan-brms/)


#### other

Tarek Amr, ["Experimenting the Bayesian way"](https://www.datascience.com/blog/experimenting-the-bayesian-way); summary of Bayesian approach with Python examples (2018-07-18)


### R

Arranged by package


#### `bayestestR`

**package**

GitHub page: [bayestestR: Utilities for analyzing Bayesian models and posterior distributions](https://github.com/easystats/bayestestR)

**articles**

easystats (2019-04-15) [Describe and understand Bayesian models and posteriors using bayestestR](https://easystats.github.io/blog/posts/bayestestr_presentation/)


#### `rjags`

**package**

CRAN page: [rjags: Bayesian Graphical Models using MCMC](https://cran.r-project.org/web/packages/rjags/index.html)

**articles**

Alicia Johnson: [Bayesian modeling with `rjags`] {link to DataCamp course removed}


#### `tidybayes`

**package**

CRAN page: [tidybayes: Tidy Data and 'Geoms' for Bayesian Models](https://cran.r-project.org/web/packages/tidybayes/index.html)

GitHub page: [Bayesian analysis + tidy data + geoms (R package)](https://github.com/mjskay/tidybayes)

**articles**

Matthew Kay, [tidybayes: Bayesian analysis + tidy data + geoms](http://mjskay.github.io/tidybayes/)


-30-
