# Machine learning {#ml}

```{r echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, cache = TRUE)
options(width = 100, dplyr.width = 100)
library(ggplot2)
theme_set(theme_light())
```


Machine learning is a growing field of data analysis where the building of models is iterated automatically. This is particularly important in areas where new data is being collected on an on-going basis (examples often used are Netflix recommendations and amazon`s "Recommended for you").

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Machine learning is basically just a fancier version of y=mx+b <a href="https://t.co/lhrUJcjvmN">https://t.co/lhrUJcjvmN</a></p>&mdash; Medium (@Medium) <a href="https://twitter.com/Medium/status/1097681613666902017?ref_src=twsrc%5Etfw">February 19, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


### Theory and methods

* [Computational learning theory](https://en.wikipedia.org/wiki/Computational_learning_theory)

* [Statistical learning theory](https://en.wikipedia.org/wiki/Statistical_learning_theory)

David Robinson, 2018-01-09, ["What's the difference between data science, machine learning, and artificial intelligence?"](http://varianceexplained.org/r/ds-ml-ai/)

Lev Reyzin, 2019-01-07, ["Unprovability comes to machine learning"](https://www.nature.com/articles/d41586-019-00012-4), _Nature_

Nicholas Harvey, [CPSC 531H: Machine Learning Theory](https://www.cs.ubc.ca/~nickhar/F18-531/), UBC Computer Science Department.

* "This is a graduate course on some theoretical aspects of machine learning. The emphasis is on foundations and on results with rigorous proofs. The viewpoint is much more computational than statistical."


### R

Laurent Gatto, 2017-10-18, [An Introduction to Machine Learning with R](https://lgatto.github.io/IntroMachineLearningWithR/index.html)

J.J. Allaire, [Machine Learning with R and TensorFlow](https://www.youtube.com/watch?v=atiYXm7JZv0&feature=youtu.be), keynote at rstudio::conf 2018 (youtube video)

David Smith, 2018-02-21, [Machine Learning in R with TensorFlow](http://blog.revolutionanalytics.com/2018/02/r-with-tensorflow.html)

Coursera: [Practical Machine Learning](https://www.coursera.org/learn/practical-machine-learning)

DataCamp tutorial: Karlijn Willems, [Machine Learning in R for beginners](https://www.datacamp.com/community/tutorials/machine-learning-in-r)

Jason Brownlee, 2016-02-23, [Your First Machine Learning Project in R Step-By-Step (tutorial and template for future projects)](https://machinelearningmastery.com/machine-learning-in-r-step-by-step/)

#### `h2o`

**package**

CRAN page: [h2o: R Interface for H2O](https://cran.r-project.org/web/packages/h2o/index.html)

**articles**

Erin LeDell, 2017, [Automatic Machine Learning in R](https://github.com/h2oai/h2o-meetups/blob/master/2017_07_05_useR_Brussels_H2O_AutoML_in_R/useR2017_automl_july2017.pdf?utm_content=bufferaca4e&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) -- presentation at UseR! Brussels


