# Regression methods {#regression}


## R

John Fox and Sanford Weisberg, [_An R Companion to Applied Regression, Second Edition_](http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/), Sage (2011)

Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani, _An Introduction to Statistical Learning: With Applications in R_, Springer (2013)

Jeremy Anglin, ["Using R to replicate common SPSS multiple regression output"](http://jeromyanglim.blogspot.ca/2013/12/using-r-to-replicate-common-spss.html) (2013-12-04)

Selva Prabhakaran, [Linear Regression](http://r-statistics.co/Linear-Regression.html) (part of the [r-statistics.co](http://r-statistics.co/) R tutorials)


***

## Logistic Regression (Generalized Linear Models, GLM)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">It&#39;s only called a Neural Network if it comes from the Neuralè region of France. Otherwise you have to call it a logistic regression.</p>&mdash; Vicki Boykis (/@/vboykis) <a href="https://twitter.com/vboykis/status/1077024069126668289?ref_src=twsrc%5Etfw">December 24, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


#### text books

Michael Friendly and David Meyer, _Discrete Data Analysis with R: Visualization and Modeling Techniques for Categorical and Count Data_, CRC Press (2016)

* see Chapter 7, "Logistic Regression Models"

Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani, _An Introduction to Statistical Learning: With Applications in R_, Springer (2013)

* Chapter 4, "Classification", includes a section on Logistic Regression

#### online resources

Tavish Srivastava, [Building a Logistic Regression model from scratch](https://www.analyticsvidhya.com/blog/2015/10/basics-logistic-regression/) (2015-10-04)

Michy Alice, [How to perform a Logistic Regression in R](https://www.r-bloggers.com/how-to-perform-a-logistic-regression-in-r/) (2015-09-13)

Data Flair, [Generalized Linear Models in R](https://data-flair.training/blogs/generalized-linear-models-in-r/), 2018-01-17  in R by Data Flair

stackoverflow: ["Confidence intervals for predictions from logistic regression"](https://stackoverflow.com/questions/14423325/confidence-intervals-for-predictions-from-logistic-regression)

http://andrewgelman.com/2017/03/04/interpret-confidence-intervals/


***
 

## Packages

#### {broom}

CRAN: [broom: Convert Statistical Analysis Objects into Tidy Tibbles](https://cran.r-project.org/package=broom)

[github page](https://github.com/tidymodels/broom)

[Introduction to broom](https://cran.r-project.org/package=broom/vignettes/broom.html)

David Robinson (2015-03-19) [broom: a package for tidying statistical models into data frames](http://varianceexplained.org/r/broom-intro/)


#### {brms}

[brms: Bayesian Regression Models using Stan](https://cran.r-project.org/package=brms)

"...an interface to fit Bayesian generalized (non-)linear multivariate multilevel models using Stan"

[github page](https://github.com/paul-buerkner/brms)


##### {brmstools}

* [tools and helpers for `brms`](https://mvuorre.github.io/brmstools/)



#### {modelr}

[github page](https://github.com/tidyverse/modelr)


***

## Quantile regression

Quantile regression](https://en.wikipedia.org/wiki/Quantile_regression) at Wikipedia



### Theory and methods

Despa, Simon. (2007/2012) ["Quantile Regression"](https://www.cscu.cornell.edu/news/statnews/stnews70.pdf), Cornell University, StatNews #70.

Dade, Brian S. and Barry R. Noon (2003) ["A gentle introduction to quantile regression for ecologists"](http://www.econ.uiuc.edu/~roger/research/rq/QReco.pdf), _Front Ecol Environ_; 1(8): 412– 420.

Koenker, Roger and Kevin F. Hallock (2001) ["Quantile Regression"](http://www.econ.uiuc.edu/~roger/research/rq/QRJEP.pdf), Journal of Economic Perspectives—Volume 15, Number 4 —Fall 2001—Pages 143–156.

Marzban, Caren. ["Quantile Regression"](http://faculty.washington.edu/marzban/quantile.pdf) Invited paper presented at the joint session between AI and Prob & Stats Conference. 88th American Meteorological Society Annual Meeting, New Orleans, Jan. 20-24, 2008. (More of Marzban's papers can be found on his [University of Washington faculty page](http://faculty.washington.edu/marzban/).

University of Virginia Library Research Data Services, ["Getting Started with Quantile Regression"](http://data.library.virginia.edu/getting-started-with-quantile-regression/).


### R

#### {quantreg}

**package**

CRAN page: [quantreg: Quantile Regression](https://cran.r-project.org/package=quantreg/)

**articles**

Koenker, Roger. (?) ["Quantile Regression in R: A Vignette"](https://cran.r-project.org/package=quantreg/vignettes/rq.pdf).


***


## Dominance Analysis


Armando B. Mendes, ["Dominance Analysis"](http://sk.sagepub.com/books/the-sage-dictionary-of-quantitative-management-research/n28.xml), Chapter 28 in _The SAGE Dictionary of Quantitative Management Research_, eds. Luiz Moutinho & Graeme Hutcheson, 2011. (paywalled)

[Dominance Analysis: Overview](https://rmc.ehe.osu.edu/files/2018/08/DominanceAnalysisFeb2018.pdf), Research Methodology Center, 2018.

* Budescu, D. V. (1993). Dominance analysis: A new approach to the problem of relative importance of predictors in multiple regression. Psychological Bulletin, 114(3), 542-551. https://doi.org/10.1037/0033-2909.114.3.542

* Azen, R., & Budescu, D. V. (2003). The dominance analysis approach for comparing predictors in multiple regression. Psychological Methods, 8(2), 129-148. https://doi.org/10.1037/1082-989X.8.2.129

* Azen, R., & Budescu, D. V. (2006). Comparing Predictors in Multivariate Regression Models: An Extension of Dominance Analysis. Journal of Educational and Behavioral Statistics, 31(2), 157-180. https://doi.org/10.3102/10769986031002157

* Azen, R., & Traxel, N. (2009). Using Dominance Analysis to Determine Predictor Importance in Logistic Regression. Journal of Educational and Behavioral Statistics, 34(3), 319-347. https://doi.org/10.3102/1076998609332754

* Luo, W., & Azen, R. (2013). Determining Predictor Importance in Hierarchical Linear Models Using Dominance Analysis. Journal of Educational and Behavioral Statistics, 38(1), 3-31. https://doi.org/10.3102/1076998612458319

* S. Yasaman Amirkiae (2016) [Dominance Analysis: A Necessity of Paying Attention to Relative Importance of Predictors in Decision Making Issues](http://www.swdsi.org/proceedings/2016/Papers/Papers/PA027.pdf)


### R

#### {dominanceanalysis}

CRAN page: [dominanceanalysis: Dominance Analysis](https://cran.r-project.org/package=dominanceanalysis/)


[GitHub page: ](https://github.com/clbustos/dominanceAnalysis)

* Dominance Analysis (Azen and Bodescu), for multiple regression models: OLS (univariate, multivariate), GLM and HLM 


#### {relaimpo}

CRAN page: [relaimpo: Relative Importance of Regressors in Linear Models](https://cran.r-project.org/package=relaimpo/)


#### {yhat}

CRAN page: [yhat: Interpreting Regression Effects](https://cran.r-project.org/package=yhat/)

-30-
