# (PART) Spatial Data {-} 



# Spatial Data (including mapping) {#spatial_data}


## Introduction

Cartographic design principles
 
* U.K. Ordnance Survey, ["Cartographic design principles"](https://www.ordnancesurvey.co.uk/resources/carto-design/carto-design-principles.html)

Choropleth maps

* vis4net, ["Why we didn’t use a cartogram in the Brexit map"](http://vis4.net/blog/posts/to-cartogram-or-not-to-cartogram-the-brexit/) (2016)



## Theory and methods

[_A Gentle Introduction to GIS_](https://docs.qgis.org/testing/en/docs/gentle_gis_introduction/index.html)


### Map projections

A rich and complicated topic in and of itself: how can the surface of a sphere be represented in a two dimensional plane without distortion? (Answer: it can't, but the distortion can be minimized to suit the purpose of the map.) 

* Randall B. Smith, 2011, [Introduction to Map Projections](https://www.microimages.com/documentation/Tutorials/project.pdf) (PDF file)

* ESRI, [Understanding Map Projections](http://downloads2.esri.com/support/documentation/ao_/710Understanding_Map_Projections.pdf) (PDF file)

* Alberto Cairo, 2019-07-31, [The Mercator projection isn't “a monstrosity"](http://www.thefunctionalart.com/2019/07/the-mercator-projection-isnt-monstrosity.html)



### Geographic references (coordinate reference systems)

[Spatial Reference](http://www.spatialreference.org/) -- URL/URI-based references to spatial reference systems, including EPSG and ESRI.

[Coordinate Reference Systems](https://docs.qgis.org/testing/en/docs/gentle_gis_introduction/coordinate_reference_systems.html) -- from [_A Gentle Introduction to GIS_](https://docs.qgis.org/testing/en/docs/gentle_gis_introduction/index.html)

British Columbia's standard is [BC Albers (EPSG:3005)](http://epsg.io/3005)

[Coordinate Reference System and Spatial Projection](https://www.earthdatascience.org/courses/earth-analytics/spatial-data-r/intro-to-coordinate-reference-systems/) -- from [Spatial Data in R](https://www.earthdatascience.org/courses/earth-analytics/spatial-data-r/), part of an Earth Analytics course.



## Canadian geography: shapefiles

**Statistics Canada** has made available a variety of boundary files.

* [Boundary files](https://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/bound-limit-eng.cfm)

* [2011 Census - Boundary files](https://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/bound-limit-2011-eng.cfm)

**DataBC** has a number of of geographic boundary files available

* [Boundaries](https://catalogue.data.gov.bc.ca/dataset?q=iso_topic_string%3A%2Aboundaries%2A)

* [Provincial Electoral Districts - Electoral Boundaries Redistribution, 2008](https://catalogue.data.gov.bc.ca/dataset/provincial-electoral-districts-electoral-boundaries-redistribution-2008)


***

## R


### Spatial Data in R: text books


Roger S. Bivand, Edzer J. Pebesma, and Virgilio Gómez-Rubio (2008) [_Applied Spatial Data Analysis with R_](http://gis.humboldt.edu/OLM/r/Spatial%20Analysis%20With%20R.pdf) {PDF version of text book}

Robin Lovelace, Jakub Nowosad, and Jannes Muenchow, [_Geocomputation with R_](https://geocompr.robinlovelace.net/)

* [presentations page](https://www.r-bloggers.com/geographic-projections-and-transformations/)

* [Geographic projections and transformations](https://geocompr.github.io/post/2019/crs-projections-transformations/) -- workbook based on Chapter 6 of _Geocomputation with R_


Edzer Pebesma and Roger Bivand, [_Spatial Data Science_](https://keen-swartz-3146c4.netlify.com/) -- textbook, work in progress.


Manuel Gimond, [Intro to GIS and Spatial Analysis](https://mgimond.github.io/Spatial/index.html) -- "compilation of lecture notes for my Introduction to GIS and Spatial Analysis course (ES214)" at Colby College, Maine.



### Spatial Data in R: blogposts, tutorials, etc.


twitter thread on "geocomputation in R":

* https://twitter.com/deanmarchiori/status/1116143933656981504

Aleszu Bajak, 2018-12-20, ["How to map point data and polygon shapefiles in R"](http://www.storybench.org/how-to-map-point-data-and-polygon-shapefiles-in-r/)

Frank Davenport (2012) ["Notes from A Recent Spatial R Class I Gave"](http://davenportspatialanalytics.squarespace.com/blog/2012/6/19/notes-from-a-recent-spatial-r-class-i-gave.html)

Nick Eubank, [Merging Spatial Data](http://www.nickeubank.com/wp-content/uploads/2015/10/RGIS2_MergingSpatialData_part1_Joins.html)

Matthias Forkel (2015) [Analysis of spatial data in R](ftp://ftp.bgc-jena.mpg.de/pub/outgoing/mforkel/Rcourse/spatialR_2015.pdf) {PDF version of presentation/lecture slide deck}

Kieran Healy, 2018-12-09, [Canada Map](https://kieranhealy.org/blog/archives/2018/12/09/canada-map/)

Tomislav Hengl, [_A Practical Guide to Geostatistical Mapping_](http://spatial-analyst.net/book/) {PDF ebook available via Lulu}

Jacinta Holloway, [raster2data](https://github.com/thejholloway/raster2data)

* "This repository provides some introductory guidance for working with spatial image files, like rasters, and converting these to dataframes in R in order to perform statistical analyses. Includes an example satellite image and R code."


Katie Jolly, 2019-08-15, [Geographic Data Science in R](http://www.katiejolly.io/rnorth-19/) -- presentation at R North 2019 conference.


Arda Kosar, 2018-05-01, [A Beginner’s Exploration of Shiny and Leaflet for Interactive Mapping](https://www.datascience.com/blog/beginners-guide-to-shiny-and-leaflet-for-interactive-mapping)

Robin Lovelace (2014) ["R, an Integrated Statistical Programming Environment and GIS"](http://robinlovelace.net/r/2014/11/28/r-as-a-gis-geoinformatics.html) {blog post}

Robin Lovelace, James Cheshire and others, 2015-, [_Introduction to visualising spatial data in R_](https://cran.r-project.org/doc/contrib/intro-spatial-rl.pdf) {or up-to-date version on github, [Robinlovelace/Creating-maps-in-R](https://github.com/Robinlovelace/Creating-maps-in-R) {tutorial}

Sharon Machlis (2016) [Create maps in R in 10 (fairly) easy steps](http://www.computerworld.com/article/3038270/data-analytics/create-maps-in-r-in-10-fairly-easy-steps.html), Computerworld (2016-03-01)

Mel Moreno and Mathieu Basille, 2018-10-25, [Drawing beautiful maps programmatically with R, sf and ggplot2](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html)


Mark Padgham, Geoff Boeing, et al., 2019-08-07, [An Introduction to Software Tools, Data, and Services for Geospatial Analysis of Stroke Services](https://www.frontiersin.org/articles/10.3389/fneur.2019.00743/full), _Frontiers in Neurology_, 07 August 2019 | https://doi.org/10.3389/fneur.2019.00743


Vivek Patil (2015) [Animated choropleths using animation, ggplot2, rCharts, googleVis, and Shiny](http://patilv.com/Animated-choropleths-using-animation-ggplot2-rCharts-googleVis-and-Shiny/) (2014-01-17)

Francisco Rodriguez-Sanchez, 2013-12-18, [Spatial data in R: Using R as a GIS](https://pakillo.github.io/R-GIS-tutorial/) {github version at [Pakillo/R-GIS-tutorial](https://github.com/Pakillo/R-GIS-tutorial/blob/master/R-GIS_tutorial.md)}


Dominic Royé, 2018-11-03, [Accessing OpenStreetMap data with R](https://dominicroye.github.io/en/2018/accessing-openstreetmap-data-with-r/)


Mithil Shah, 2016-04-18, [R and GIS – working with shapefiles](http://www.studytrails.com/r/r-and-gis-working-with-shapefiles/)


Andrew Tran, 2019, [Mapping with R NICAR19 session](https://github.com/andrewbtran/NICAR/tree/master/2019/mapping)

#### other

[R Spatial Cheatsheet](http://www.maths.lancs.ac.uk/~rowlings/Teaching/UseR2012/cheatsheet.html) {from Barry Rowlingson's [Geosppatial Data in R and Beyond](http://www.maths.lancs.ac.uk/~rowlings/Teaching/UseR2012/index.html) tutorial site}

[Maps and Data Visualisations with R](http://spatial.ly/r/) (from [spatial.ly](spatial.ly))

[Maps in R](https://sesync-ci.github.io/maps-in-R-lesson/)

Sharp Sight Labs, [Simple practice: basic maps with the Tidyverse](http://sharpsightlabs.com/blog/simple-practice-maps-tidyverse/)


[Introduction to Geospatial Raster and Vector Data with R](https://datacarpentry.org/r-raster-vector-geospatial/) -- [Data Carpentry](https://datacarpentry.org/) lesson



#### tips and tricks


[creating a spatial object](http://stackoverflow.com/questions/29736577/how-to-convert-data-frame-to-spatial-coordinates)

[Mapping (historic) tracks in ggplot2](http://spatial.ly/2016/10/mapping-historic-tracks-ggplot2/)

[geostat-course.org](http://geostat-course.org/aggregator/sources/2?page=24&ui=default)


[Making Maps with R](http://www.molecularecologist.com/2012/09/making-maps-with-r/)


[Opening shapefile in R?](https://gis.stackexchange.com/questions/19064/opening-shapefile-in-r)



### Canadian examples: maps in R

[Canadian census map division in R](http://www.scriptscoop2.com/t/9bec270a9183/canadian-census-map-division-in-r.html)

[Choropleth Maps with R and ggplot2](http://unconj.ca/blog/choropleth-maps-with-r-and-ggplot2.html)



***


## R Packages

### `{cartography}`

github page: [cartography](https://github.com/riatelab/cartography)


### `{choroplethr}`

**package**

CRAN page: [choroplethr: Simplify the Creation of Choropleth Maps in R](https://cran.r-project.org/package=choroplethr)

**articles**

[Ari Lamstein's blog](http://www.arilamstein.com/blog/)

[Combining Choropleth Maps and Reference Maps in R](http://www.arilamstein.com/blog/2015/09/30/combining-choropleth-maps-and-reference-maps-in-r/)

[Creating Administrative Choropleth Maps Using R](https://www.gislounge.com/creating-administrative-maps-using-r/)

[Easy data maps with R: the choroplethr package](http://blog.revolutionanalytics.com/2014/01/easy-data-maps-with-r-the-choroplethr-package-.html)

[How to Change the Reference Map in Choroplethr](http://www.arilamstein.com/blog/2015/10/08/how-to-change-the-reference-map-in-choroplethr/)



### `{ggmap}`

**package**

CRAN page: [ggmap: Spatial Visualization with ggplot2]
(https://cran.r-project.org/package=ggmap)

**articles**

[Creating a custom soil attribute plot using ggmap](http://blog.revolutionanalytics.com/2015/01/creating-a-custom-soil-attribute-plot-using-ggmap.html)

Laura Ellis, 2018-04-15, [Map Plots Created With R And ggmap](https://www.littlemissdata.com/blog/maps)

David Kahle and Hadley Wickham, [ggmap: Spatial Visualization with ggplot2](https://journal.r-project.org/archive/2013-1/kahle-wickham.pdf) _The R Journal_ Vol. 5/1, June 2013, pp.144-161.

[Plotting Choropleths from Shapefiles in R with ggmap – Toronto Neighbourhoods by Population](http://www.r-bloggers.com/plotting-choropleths-from-shapefiles-in-r-with-ggmap-toronto-neighbourhoods-by-population/)

[R & GGMap Visualization Case Study](http://www.r-bloggers.com/r-ggmap-visualization-case-study/)

[Visualising Crime Hotspots in England and Wales using {ggmap}](http://www.r-bloggers.com/visualising-crime-hotspots-in-england-and-wales-using-ggmap-2/)



### `{ggspatial}`

**package**

CRAN page: [ggspatial: Spatial Data Framework for ggplot2]
(https://cran.r-project.org/package=ggspatial)

gihub page: [A ggplot2 R extension for plotting Spatial objects](https://github.com/paleolimbot/ggspatial)


### `{GISTools}`

**package**

CRAN page: [GISTools: Some further GIS capabilities for R]
(https://cran.r-project.org/package=GISTools)

**articles**


### `{idbr}`

**package**

CRAN page: [idbr: R Interface to the US Census Bureau International Data Base API](https://cran.r-project.org/package=idbr/)

github page: [idbr](https://github.com/walkerke/idbr)

**articles**

Kyle Walker, [Visualizing international demographic indicators with idbr and Plotly](http://walkerke.github.io/2016/01/idbr/)


### `{leaflet}`

**package**

CRAN: [leaflet: Create Interactive Web Maps with the JavaScript 'Leaflet' Library](https://cran.r-project.org/package=leaflet)

RStudio on github: [rstudio/leaflet](https://github.com/rstudio/leaflet)

**articles**

[Leaflet for R](http://rstudio.github.io/leaflet/)

[Using Leaflet with Shiny](https://rstudio.github.io/leaflet/shiny.html)

Robin Lovelace, [The leaflet package for online mapping in R](https://www.r-bloggers.com/the-leaflet-package-for-online-mapping-in-r/)

Kyle Walker (2015) ["Creating a Leaflet choropleth map with a pop-up in R"](https://rpubs.com/walkerke/leaflet_choropleth) (2015-01-30)

Kyle Walker (2016) ["Using a new Mapbox Studio map in an R Leaflet project"](https://rpubs.com/walkerke/rstudio-mapbox) (2016-05-18)

[Leaflet: an open-source JavaScript library for mobile-friendly interactive maps](http://leafletjs.com/)


### `{sf}`

**package**

CRAN: [sf: Simple Features for R](https://cran.r-project.org/package=sf)




### `{sp}`

**package**

CRAN: [sp: Classes and Methods for Spatial Data](https://cran.r-project.org/package=sp)

vignettes: Edzer Pebesma and Roger S. Bivand (2005): [Classes and Methods for Spatial Data: the sp Package](https://cran.r-project.org/package=sp/vignettes/intro_sp.pdf)


**articles**

Edzer Pebesma (2008) [Introduction to R and package sp](http://pebesma.staff.ifgi.de/Aufbaukurs/R/slides_R.pdf)


### `{tmap}`

**package**

CRAN: [tmap: Thematic Maps](https://cran.r-project.org/package=tmap)

vignettes: [tmap in a nutshell](https://cran.r-project.org/package=tmap/vignettes/tmap-nutshell.html)

GitHub: [`tmap`](https://github.com/mtennekes/tmap)


**articles**

Corentin M. Barbu, 2015-11-06, ["tmap R package"](http://spatcontrol.net/SpatialControl/2015/11/06/tmap-r-package/)



### `{urbnmapr}`

**articles**

Sarah Strochak, [How to Create State and County Maps Easily in R](https://medium.com/@urban_institute/how-to-create-state-and-county-maps-easily-in-r-577d29300bb2)


***

