# (PART) Other methods {-} 


# Text Analysis and Text Mining {#textanalysis}




## Introduction

Most "data analysis" has been focussed on quantitative methods, but in recent years text analysis and text mining methods have been developed in concert with natural language processing (NLP).


## Theory and methods

Shawn Graham, Ian Milligan, and Scott Weingart (2015) "Topic Modeling: A Hands-On Adventure in Big Data", chapter four of [@Graham_etal_2015]

- See the companion website, [Exploring Big Historical Data: The Historian's Macroscope](http://www.themacroscope.org/2.0/)




## R

**The definitive guide**

Julia Silge and David Robinson (2016) [_Tidy Text Mining with R_](http://tidytextmining.com/) {most recent version dated 2016-12-19}

**other general resources**

Super User, 2019-02-04, [An overview of the NLP ecosystem in R (#nlproc #textasdata)](https://www.r-bloggers.com/an-overview-of-the-nlp-ecosystem-in-r-nlproc-textasdata/)


### Some examples

David Robinson (2016) ["Text analysis of Trump's tweets confirms he writes only the (angrier) Android half"](http://varianceexplained.org/r/trump-tweets/) (2016-08-09)

Julia Silge (2016) ["You Must Allow Me To Tell You How Ardently I Admire and Love Natural Language Processing"](http://juliasilge.com/blog/You-Must-Allow-Me/) (2016-03-08)


### Packages


#### CRAN Task View: NLP

[CRAN Task View: Natural Language Processing](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html)

- "This CRAN task view collects relevant R packages that support computational linguists in conducting analysis of speech and language on a variety of levels - setting focus on words, syntax, semantics, and pragmatics."


#### `monkeylearn`

**package**

CRAN page: [monkeylearn: Accesses the Monkeylearn API for Text Classifiers and Extractors](https://cran.r-project.org/package=monkeylearn)

github page: [monkeylearn: R package for text analysis with Monkeylearn](https://github.com/ropensci/monkeylearn)

**articles**



#### `quanteda`

[quanteda.io](http://quanteda.io/)


**package**

CRAN page: [quanteda: Quantitative Analysis of Textual Data](https://cran.r-project.org/package=quanteda)


**articles**

["Getting Started with `quanteda`"](https://cran.r-project.org/package=quanteda/vignettes/quickstart.html) (package vignette)


#### `tidytext`

**package**

CRAN page: [tidytext: Text Mining using 'dplyr', 'ggplot2', and Other Tidy Tools](https://cran.r-project.org/package=tidytext/)

github repo: [tidytext on github](https://github.com/juliasilge/tidytext)

**articles**

Julia Silge, ["Term Frequency and tf-idf Using Tidy Data Principles"](http://juliasilge.com/blog/Term-Frequency-tf-idf/), 2016-06-27

[]()

Julia Silge and David Robinson (2016-10-27) ["Introduction to `tidytext`"](https://cran.r-project.org/package=tidytext/vignettes/tidytext.html) (package vignette)


#### `tm`

**package**

CRAN page: [tm: Text Mining Package](https://cran.r-project.org/package=tm)


**articles**

Inigo Feinerer (2015) ["Introduction to the `tm` Package: Text Mining in R"](https://cran.r-project.org/package=tm/vignettes/tm.pdf) (package vignette)

Ingo Feinerer, Kurt Hornik, David Meyer (2007) ["Text Mining Infrastructure in R"](https://www.jstatsoft.org/article/view/v025i05), _Journal of Statistical Software_, 25 (5).



***


