# Presentations {#presentations}



## Introduction

Giving presentations--talks, lectures, keynotes--is something that every data scientist is going to be called upon to do. Giving _effective_ presentations is a skill that can be learned.


## Theory and methods

I always recommend two books when I get asked about this topic: Garr Reynold's _Presentation Zen_ [@Reynolds_2008] and Nancy Duarte's _slide:ology_ [@Duarte_2008]. There's an ever-so-small amount of overlap between the two, just enough to reinforce the other.

The sub-title of Reynold's book is "simple ideas on presentation design and delivery", and that's as succicnt a description as you could hope for. The associated website has further details, including this post on the website which has the following ["10 tips for Improving Your Presentations Today "](https://www.presentationzen.com/presentationzen/2014/11/10-tips-for-improving-your-presentations-lectures-speeches.html) (actually 11 tips):

1. Turn off the computer

2. Put the audience first

3. Have a solid structure

4. Have a clear theme

5. Remove the nonessential

6. Hook 'em early

7. Show a clear conflict

8. Demonstrate a clear change

9. Show or do the unexpected

10. Make 'em feel

11. Be authentic


Nancy Duarte's book delves deeper into the technical elements of good presentations, from layout to the use of colour. These design elements support the structural ideas that Reynolds promotes; hand in hand, the two books cover the core requirements for making great presentations.



**articles**


Melinda Seckington, 2017-07-29, [The Art of Slide Design](https://speakerdeck.com/mseckington/the-art-of-slide-design)

Kieran Healy, 2018-03-24, [Making Slides](https://kieranhealy.org/blog/archives/2018/03/24/making-slides/)

Jessica Calarco, July 31, 2018-07-31, [Conference Talks](http://www.jessicacalarco.com/tips-tricks/2018/7/31/conference-talks)


**general tips and pointers**

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Some of my tips for new JSM speakers: <br><br>🔘 Avoid complete sentences on slides. They are only cues. You are a speaker, not a reader.<br><br>🔘 Try not to spend too much time on background. Your focus should be YOUR work, not others’ <br><br>🔘 Spend the most time describing plots <a href="https://twitter.com/hashtag/JSM2018?src=hash&amp;ref_src=twsrc%5Etfw">#JSM2018</a></p>&mdash; Dr. Sam Tyner (/@/sctyner) <a href="https://twitter.com/sctyner/status/1024776569271668736?ref_src=twsrc%5Etfw">August 1, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>



### R


#### `xaringan` - presentations in R Markdown

**package**

CRAN: [xaringan: Presentation Ninja](https://cran.r-project.org/web/packages/xaringan/index.html)

github: [`xaringan`](https://github.com/yihui/xaringan)

wiki: [`xaringan` wiki](https://github.com/yihui/xaringan/wiki)

**articles**

Yihui Xie, J. J. Allaire, Garrett Grolemund (2018) [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/xaringan.html) (link to xaringan chapter (most recent update I've noted: 2018-06-02)

Yihui Xie, 2017-08-31, [Incremental Slides with xaringan / remark.js](https://slides.yihui.name/xaringan/incremental.html#1)

Yihui Xie, 2017-10-03, [Help Me: xaringan / remark.js CSS Themes?](https://yihui.name/en/2017/10/xaringan-themes/)

Daniel Anderson, 2018-06-02, (Contribute to Open Source with Pretty Slides)[http://www.datalorax.com/talks/cascadia18/#1]

Alison Presmanes Hill, 2017-12-18, [R-Ladies presentation ninja](https://alison.rbind.io/post/r-ladies-slides/)

Nan-Hung Hsieh, [TAMU Presentation Template](https://nanhung.rbind.io/slide/tamu-slide-template.html#1)

John R. Little, 2017-08-09, [Compose Slides in R with Xaringan Slides](https://www.johnlittle.info/post/compose-slides-in-r-with-xaringan-slides/)

* [Duke University slide template](https://github.com/libjohn/slide-template-dukeu)

Steven V. Miller, 2018-02-03, [Make Your Presentations Fun in Xaringan](http://svmiller.com/blog/2018/02/r-markdown-xaringan-theme/)

**xaringan tips and tricks**

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I&#39;m not a ninja, but sharing my favorite <a href="https://twitter.com/hashtag/xaringan?src=hash&amp;ref_src=twsrc%5Etfw">#xaringan</a> tricks we talked about in the Advanced R Markdown workshop at <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a>. Slides are here: <a href="https://t.co/z4FZ1cgRuJ">https://t.co/z4FZ1cgRuJ</a><br><br>First up: name your slides! Makes it easier to link out and cross reference within deck <a href="https://t.co/zVswMzkivf">https://t.co/zVswMzkivf</a> <a href="https://t.co/HrOF4t5juG">pic.twitter.com/HrOF4t5juG</a></p>&mdash; Alison Hill (/@/apreshill) <a href="https://twitter.com/apreshill/status/1085659933238976513?ref_src=twsrc%5Etfw">January 16, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

[Advanced R Markdown training](http://arm.rbind.io/) - from RStudio conference, 2019-01-15/16


**CSS tips and tricks**

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">This is one of the best explanations I&#39;ve seen of the CSS background-size properties contain vs cover: <a href="https://t.co/D5dzSmvbs0">https://t.co/D5dzSmvbs0</a><br><br>If you are an <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/xaringan?src=hash&amp;ref_src=twsrc%5Etfw">#xaringan</a> user (remark.js), this is *very* helpful for understanding when to use which size property with a background image! <a href="https://t.co/SLI2jMEPf7">pic.twitter.com/SLI2jMEPf7</a></p>&mdash; Alison Hill (/@/apreshill) <a href="https://twitter.com/apreshill/status/1075239136691277824?ref_src=twsrc%5Etfw">December 19, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>



-30-
