# RMarkdown {#RMarkdown}



## Introduction

This section provides links to resources for using the various packages that use R Markdown.

**_Why_ would you want to use R Markdown?**

* Rob Hyndman (2020-01-30) [R Markdown changed my life](https://robjhyndman.com/seminars/rmarkdown/) -- presentation at rstudio::conf 2020

* David Keyes (2019-03-29) [R’s Killer Feature: RMarkdown](https://rfortherestofus.com/2019/03/r-killer-feature-rmarkdown/)

**_How_ can you use R Markdown?**

* Thomas Mock, 2020-07-24, [How I share knowledge around R Markdown: A meta collection of some R Markdown strategies](https://themockup.blog/posts/2020-07-25-meta-rmarkdown/)



## R Markdown

Yihui Xie, Christophe Dervieux, Emily Riederer, [_R Markdown Cookbook_](https://bookdown.org/yihui/rmarkdown-cookbook/), 2020-09-21


Yihui Xie, J. J. Allaire, Garrett Grolemund (2018) [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) 

[R Markdown](http://rmarkdown.rstudio.com/), main page at R Studio

* [R Markdown Reference Guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)

* [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)

Neil Collins, _How to Create Reports In R Markdown_, a series of blog posts

* [I: Data Tables](https://www.sportscidata.com/2019/04/04/how-to-create-interactive-reports-with-r-markdown-part-i/) (2019-04-04)

* [II: Data Visualisation](https://www.sportscidata.com/2019/04/12/using-data-visualisation-in-r-markdown/) (2019-04-12)

* [III: Reactive Elements](https://www.sportscidata.com/2019/04/19/how-to-create-interactive-reports-in-r-markdown-shiny-reactive-elements/) (2019-04-19)

* [IV: Shiny App Calendar Heatmap](https://www.sportscidata.com/2019/04/26/how-to-create-reports-in-r-markdown-shiny-app-calendar-heatmap/) (2019-04-26)


Yan Holtz, [Pimp my RMD: a few tips for R Markdown](https://holtzy.github.io/Pimp-my-rmd/) (most recent update: 2018-12-10) -- a nice summary of tips, tricks, and tweaks for  your RMD files


Thea Knowles, [Dissertating with RMarkdown and Bookdown](https://bookdown.org/thea_knowles/dissertating_rmd_presentation/) -- "A preliminary tutorial led by Thea Knowles for the R-Ladies #LdnOnt workshop series"


Pete Mohanty (2017-11-07) [Automating Summary of Surveys with RMarkdown](https://rviews.rstudio.com/2017/11/07/automating-summary-of-surveys-with-rmarkdown/)


Andrew MacDonald (2018-02-09) [How I use Rmarkdown](http://thestudyofthehousehold.com/post/how-i-use-rmarkdown/) -- three handy tips on how to use markdown.

Emily Riederer (2019-05-04) [RMarkdown Driven Development (RmdDD)](https://emilyriederer.netlify.com/post/rmarkdown-driven-development/)

Nick Strayer (2019-09-04) [Building a data-driven CV with R](https://livefreeordichotomize.com/2019/09/04/building_a_data_driven_cv_with_r/)

Nicholas Tierney (2019-07-02) [RMarkdown for Scientists](https://rmd4sci.njtierney.com/) -- "This is a book on rmarkdown, aimed for scientists. It was initially developed as a 3 hour workshop, but is now developed into a resource that will grow and change over time as a living book."



### Distill

* RStudio, [Creating a Blog: Create a blog to publish a collection of Distill articles](https://rstudio.github.io/distill/blog.html)


### YAML

Your RMarkdown documents are going to have a YAML at the top of the page.

[The YAML Fieldguide](http://ymlthis.r-lib.org/articles/yaml-fieldguide.html)


***

## Packages

### `{blogdown}`

Yihui Xie, Amber Thomas, Alison Presmanes Hill, [blogdown: Creating Websites with R Markdown][@Xie_etal_blogdown_2019]

[Summer of blogdown](https://summer-of-blogdown.netlify.com/) -- series of blogposts with a step-by-step creation of a blog using blogdown


#### building a blog using {blogdown}

Esteban Moro, _Setting up your blog with RStudio and blogdown_

* [I: Creating the blog](http://estebanmoro.org/post/2019-02-02-setting-up-your-blog-with-rstudio-and-blogdown-i-creating-the-blog/) (2019-02-01)

* [II: Workflow](http://estebanmoro.org/post/2019-02-01-setting-up-your-blog-with-rstudio-and-blogdown/) (2019-02-02)

* [III: modify your theme](http://estebanmoro.org/post/2019-02-04-setting-up-your-blog-with-rstudio-and-blogdown-iii-modify-your-theme/) (2019-02-04)


Malcolm Barrett, [Move R Markdown HTML slides to Blogdown and Push to Web](https://gist.github.com/malcolmbarrett/7c5935d1734016dcb0b2c81b9bc3b549)

Yin-Ting Chou (2018-05-06) [Jekyll Website with Github, Github Pages and R Markdown](https://yintingchou.com/posts/jekyll-website-with-github-github-pages-and-r-markdown/)

Alison Hill (2017-06-12) [Up & Running with blogdown](https://alison.rbind.io/post/2017-06-12-up-and-running-with-blogdown/)

Alison Hill, _A Spoonful of Hugo_ series of blog posts:

* [Archetypes](https://alison.rbind.io/post/2019-02-19-hugo-archetypes/) (2019-02-19)

* [The netlify.toml File](https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/) (2019-02-20)

* [Page Bundles](https://alison.rbind.io/post/2019-02-21-hugo-page-bundles/) (2019-02-21)

* [Troubleshooting Your Build](https://alison.rbind.io/post/2019-03-04-hugo-troubleshooting/) (2019-03-04)




### `{bookdown}`

Yihui Xie, [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)



### `{posterdown}`

For academic conference-style posters.

[github page](https://github.com/brentthorne/posterdown#readme)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">My hyper-minimalist attempt at a “1-minute research poster.” (Main finding can be read in ~10 seconds, more detail in sidebar can be read in ~45seconds). <a href="https://twitter.com/hashtag/posterposter?src=hash&amp;ref_src=twsrc%5Etfw">#posterposter</a> (1/2) <a href="https://t.co/VcCcZwK9Xd">pic.twitter.com/VcCcZwK9Xd</a></p>&mdash; Mike Morrison (@mikemorrison) <a href="https://twitter.com/mikemorrison/status/1132687984938106882?ref_src=twsrc%5Etfw">May 26, 2019</a></blockquote>



### `{redoc}`

[redoc - Reversible Reproducible Documents](https://noamross.github.io/redoc/)

* "a package to enable a two-way R Markdown Microsoft Word workflow. It generates Word documents that can be de-rendered back into R Markdown, retaining edits on the Word document, including tracked changes."

GitHub: [noamross/redoc](https://github.com/noamross/redoc)



### `{tufte}`

An extension to {bookdown}, allows the creation of handouts in the style developed by Edward Tufte.

See:

* [Chapter 6: Tufte Handouts](https://bookdown.org/yihui/rmarkdown/tufte-handouts.html) in Yihui Xie, J. J. Allaire, Garrett Grolemund (2018) [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) 

* [Tufte Handouts](https://garrettgman.github.io/rmarkdown/tufte_handout_format.html)

  - [example code for Tufte Handout](https://raw.githubusercontent.com/rstudio/tufte/master/inst/rmarkdown/templates/tufte_html/skeleton/skeleton.Rmd)
  
  -  [tufte_handout: Tufte handout formats (PDF and HTML)](https://rdrr.io/cran/tufte/man/tufte_handout.html) -- function reference

#### `{tint}`: tint is not tufte

Package to extend range of formatting choices under the {tufte} package

* [tint](http://dirk.eddelbuettel.com/code/tint.html)



***

## `{Shiny}`

Colin Fay, 2019-04-29, [Building a Shiny App as a Package](https://www.r-bloggers.com/building-a-shiny-app-as-a-package/) (via [R-bloggers.com](https://www.r-bloggers.com/))



Carson Sievert, 2019-05-14, [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/) 



Florianne Verkroost, 2019-10-09, [Building Interactive World Maps in Shiny](https://rviews.rstudio.com/2019/10/09/building-interactive-world-maps-in-shiny/)



### shinyapps.io

RStudio's cloud hosting of your shiny apps

*[shinyapps.io user guide](https://docs.rstudio.com/shinyapps.io/index.html)


***

## Other reference materials

Dean Attalli (2015-03-24) [Knitr's best hidden gem: spin](http://deanattali.com/2015/03/24/knitrs-best-hidden-gem-spin/)


***

