# Data science pedagogy & andragogy 

## Introduction

Since it's a relatively new field, it's not surprising that the best way to teach data science is still evolving. Below are some resources for those who are sorting out how to teach this cross-silo discipline.


## General

Greg Wilson, [Teaching Tech Together: How to create and deliver lessons that work
and build a teaching community around them](https://teachtogether.tech/) -- everything the sub-title says, and more

* https://drive.google.com/drive/folders/13ohFt3D0EJ5PDbMaWTxnHH-hwA7G0IvY

* https://twitter.com/gvwilson/status/1190725151769411585?s=20


Joyce Cahoon, [Things I Wish I Knew Before I Started Teaching](https://jcahoon.netlify.com/post/2019/07/13/things-i-wish-i-knew-before-i-started-teaching/)

Felienne Hermans, 2019, [Explicit Direct Instruction in Programming Education](https://resources.rstudio.com/rstudio-conf-2019/opening-keynote-day2), keynote at RStudio::conf2019




Advice for new lecturers:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Interview went well yesterday, thanks for all the messages of support. My favourite question... You are talking to a new lecturer and they are asking for advice. What are 3 pieces of advice you would give them about teaching? thread 1/4</p>&mdash; Dr Jenny Richmond (@JenRichmondPhD) <a href="https://twitter.com/JenRichmondPhD/status/1154197750243741696?ref_src=twsrc%5Etfw">July 25, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

and a reply:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">These are good. I would add:<br>- Not every lecture will go well. Learn from the bad ones but don’t obsess over them. <br>- Teaching is a gas and expands to fill available space. If you need to also do something else (like teaching or admin) protect that time even if ... <a href="https://t.co/corUeemG1Q">https://t.co/corUeemG1Q</a></p>&mdash; Dan Simpson (@dan_p_simpson) <a href="https://twitter.com/dan_p_simpson/status/1154262404395491328?ref_src=twsrc%5Etfw">July 25, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 


***

## Andragogy

> Andragogy: the method and practice of teaching adult learners; adult education.


Knowles developed four principles of andragogy:

1. **Involved adult learners**  -- learners need to be involved in the planning and evaluation of their instruction

2. **Experience** (including mistakes) provides the basis for the learning activities

3. **Relevance and impact** -- adults are most interested in learning subjects that have immediate relevance and impact to their job or personal life

4. **Problem centred** rather than content-centred

(adapted from https://knowlestheories.weebly.com/principles-of-andragogy.html)


Malcolm S. Knowles, [_The Modern Practice of Adult Education_](https://pdfs.semanticscholar.org/8948/296248bbf58415cbd21b36a3e4b37b9c08b1.pdf) -- chapter 4, "What is Andragogy?"


[Andragogy Visually Explained for Teachers](https://www.educatorstechnology.com/2015/03/andragogy-visually-explained-for-teachers.html), 2015-03-26

Bruce D. Watson, 2015-05-05, [Adult learning theory and the six principles of adult learning](https://brucedwatson.wordpress.com/2015/05/05/adult-learning-theory-and-the-six-principles-of-adult-learning/)

https://www.med.mun.ca/getdoc/99c39da7-a8ac-40c8-9d6b-91b1a7bb3d0e/Principles-of-Adult-Learning-separate-file.aspx

https://calp.ca/blog/adult-learning-principles.htm

https://www.cpd.utoronto.ca/wp-content/uploads/2018/02/Quick-Tips-Adult-Learning-Principles.pdf

https://fmf.cfpc.ca/wp-content/uploads/2016/11/F134230_What-Do-Adult-Learners-Want.pdf

David C. M. Taylor & Hossam Hamdy (2013) Adult learning theories: Implications for learning and teaching in medical education: AMEE Guide No. 83[@Taylor_Hamdy_2013]

Ryerson University, Learning & Teaching Office, [Engaging Adult Learners](https://www.ryerson.ca/content/dam/lt/resources/handouts/EngagingAdultLearners.pdf)


***

### Tools for learning

Amelia McNamara, 2015, [Bridging the Gap Between Tools for Learning and for Doing Statistics](https://escholarship.org/uc/item/1mm9303x) -- PhD Dissertation, UCLA

Amelia McNamara, 2019, [Why the tidyverse?](http://www.amelia.mn/WhyTheTidyverse.pdf) -- slides for noRth 2019 talk


Evangeline Reynolds, 2019-08-08, [Flipbooks](https://evamaerey.github.io/little_flipbooks_library/about/what_the_flipbook)


***

### Lesson planning

https://www.algonquincollege.com/profres/lesson-planning/

https://carleton.ca/edc/teachingresources/course-design/lesson-planning/

RStudio: https://drive.google.com/drive/folders/13ohFt3D0EJ5PDbMaWTxnHH-hwA7G0IvY 

### Inclusivity 

https://www.chronicle.com/interactives/20190719_inclusive_teaching


Jane Margolis and Allan Fisher, 2001, [Unlocking the Clubhouse: Women in Computing](https://mitpress.mit.edu/books/unlocking-clubhouse) -- "Understanding and overcoming the gender gap in computer science education."


* Philip Guo, January 2014, [My book notes on Unlocking the Clubhouse](http://pgbovine.net/unlocking-the-clubhouse-notes.htm)


*** 

## Data sources

Kim, A. Y, Ismay, C., & Chunn, J. (2018). The fivethirtyeight R Package: "Tame Data" Principles for Introductory Statistics and Data Science Courses. _Technology Innovations in Statistics Education_, 11(1). Retrieved from https://escholarship.org/uc/item/0rx1231m

See also [@datasources]

***

## Teaching R

Wisdom from Roger Peng:

> You have to decide how to teach this topic...you have to decide how to present this material, and in what order. 
> Are you teaching people how to analyze data, or are you teaching people a programming language?

Not So Standard Deviations, [Episode 84 "All the Easy Issues"](http://nssdeviations.com/84-all-the-easy-issues) (discussion starting at ~39:45)


[Learning R - Resources](https://github.com/data-datum/learning_R) -- a list of resources for learning R


### Tidying data

https://twitter.com/EvaMaeRey/status/1184633134547001344?s=20


### Text books, etc

See [@Statistics and other quantitative methods: courses and text books]

### Why `<-` and not `=`

See this thread:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">1/ A not so short history/thread on my transformation how I taught (and thought of) variable assignment in <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a>: <br><br>&#39;&lt;-&#39; has major conceptual/semantic advantages over &#39;=&#39; <a href="https://t.co/K9JyontXI3">https://t.co/K9JyontXI3</a></p>&mdash; Derek Beaton (\@derek__beaton) <a href="https://twitter.com/derek__beaton/status/1162131286720491520?ref_src=twsrc%5Etfw">August 15, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

***


## RStudio cloud

RStudio [Class materials for Teach the Tidyverse, a Train-the-trainer workshop](https://github.com/rstudio-education/teach-the-tidyverse)

(whole thread)
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">This semester I have switched to teaching my <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> course in Rstudio Cloud. It works like a charm and the students enjoy it too. There is no endless debugging individual computers &amp; students can get right to the fun since I can make sure everything works in advance. <a href="https://t.co/6VRYVQg2S7">pic.twitter.com/6VRYVQg2S7</a></p>&mdash; Fabio Votta📊🦉 (@favstats) <a href="https://twitter.com/favstats/status/1082761269961281536?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


***

## More R-based teaching tools

[PsyTeachR](https://github.com/psyteachr/webex)



***

## Syllabi

Andrew Heiss, [PMAP 8521: Program Evaluation](https://evalf19.classes.andrewheiss.com/syllabus/#pep-talk), Georgia State University

* [Pep talk](https://evalf19.classes.andrewheiss.com/syllabus/#pep-talk)


Iain Carmichael, [STOR 390: Introduction to Data Science](https://idc9.github.io/stor390/), Department of Statistics, University of Washington


[Steal this syllabus! (or, how I taught Scientific Writing)](https://scientistseessquirrel.wordpress.com/2018/05/01/steal-this-syllabus-or-how-i-taught-scientific-writing/)



## Ideas on what to teach / learn


### plagiarize from these

Genomics in R
https://carpentrieslab.github.io/genomics-r-intro/

Data Science in the Tidyverse (Amelia McNamara)
https://github.com/AmeliaMN/data-science-in-tidyverse


data science for economists: 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I&#39;m teaching a &quot;data science for economists&quot; course this semester. <br><br>If you&#39;re interested in learning more about <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a>, Git(Hub), programming, databases, cloud computation, ML, etc., I&#39;ll be making all of my course material publicly available here: <a href="https://t.co/ApJo7Nuo7d">https://t.co/ApJo7Nuo7d</a> <a href="https://t.co/9gbMb2winV">pic.twitter.com/9gbMb2winV</a></p>&mdash; Grant McDermott (@grant_mcdermott) <a href="https://twitter.com/grant_mcdermott/status/1083072663440961536?ref_src=twsrc%5Etfw">January 9, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


Nick Huntington-Klein, [ECON 305:](http://www.nickchk.com/econ305.html) (2019)


https://medium.com/airbnb-engineering/empowering-data-science-with-data-engineering-education-ef2acabd3042

* source: https://twitter.com/peteskomoroch/status/1086868119514038273


Data Carpentry One Day Workshop

* https://uf-carpentry.github.io/2018-10-04-ufii-one-day/


R Programming (on Coursera): https://www.coursera.org/learn/r-programming


### This thread!

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> hive mind and especially <a href="https://twitter.com/djnavarro?ref_src=twsrc%5Etfw">@djnavarro</a> - what do you think is the most essential thing students should be taught on a one (! I know) day R and applied statistics class?</p>&mdash; Elizabeth Davis (@__EODavis) <a href="https://twitter.com/__EODavis/status/1157786328597032961?ref_src=twsrc%5Etfw">August 3, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 


Mine Cetinkaya-Rundel (2019-06-25) [Let them eat cake (first)!](https://speakerdeck.com/minecr/let-them-eat-cake-first)



### course structure ideas


#### Flipped classroom

Alyssa P. Lawson, Caylor R. Davis, and Ji Y. Son, [Not All Flipped Classes are the Same: Using Learning Science to Design Flipped Classrooms](https://scholarworks.iu.edu/journals/index.php/josotl/article/view/25856/33709), _Journal of the Scholarship of Teaching and Learning_, Vol. 19, No. 5, December 2019

Jennifer R. Winquist and Kieth A. Carlson, [Flipped Statistics Class Results: Better Performance Than Lecture Over One Year Later ](http://jse.amstat.org/v22n3/winquist.pdf), _Journal of Statistics Education_, Volume 22, Number 3 (2014)


#### _R learning sprint_

See whole thread:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I sent him a quick list of things I wanted to cover: <br>-Set up the basic R workspace (eg R script vs R project)<br>-Read &amp; write data (CSV, Excel, and Stata)<br>-Reshape<br>-Run simple tabs (means, variances, etc.)<br>-Working with strings and number formats<br>-Switch bw data sets</p>&mdash; Jon Schwabish (@jschwabish) <a href="https://twitter.com/jschwabish/status/1075150270290649088?ref_src=twsrc%5Etfw">December 18, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


### next

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">If you were learning the basics of R for the first time, what would you want to know in the first two hours?</p>&mdash; Colin J. Carlson (@ColinJCarlson) <a href="https://twitter.com/ColinJCarlson/status/1082480937101942784?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

replies:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Basic vocab stuff. What are &quot;functions&quot;, &quot;objects&quot;, &quot;values&quot;, &quot;vectors&quot;, &quot;environments&quot;, etc. What does it mean to &quot;assign&quot;? Really basic things.</p>&mdash; Nelson Stauffer (@NelsonStauffer) <a href="https://twitter.com/NelsonStauffer/status/1082498812629774336?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">how to read in data, how to graph the data, how to find help to do whatever I want to do in R next, how to trouble shoot error messages</p>&mdash; Auriel Fournier (@RallidaeRule) <a href="https://twitter.com/RallidaeRule/status/1082619705804943360?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Assuming I had no coding experience at all... how to &quot;see&quot; and change your R objects. Things like head, str,... and how to create and manipulate dataframes, matrices, etc.</p>&mdash; Dr Maureen Berg, microboiologist (@MaureenBug) <a href="https://twitter.com/MaureenBug/status/1082482010214477825?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Assuming they&#39;re coming from non-coding or excel background, give instant success. Read a CSV and make a bar graph, then change it to a beeswarm plot, then add color and style and make it interactive with a quick ggplotly.</p>&mdash; William Chase (@W_R_Chase) <a href="https://twitter.com/W_R_Chase/status/1082501683576557569?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">For beginners, I suggest importing/exporting multiple file types, data inspection/cleaning (head, class, level, removing empties/NAN, removing, sorting, &amp; naming rows and columns), data structures, line code for removing stored info (variables &amp; graphics), &amp; SUBSET!!!</p>&mdash; Sarah PhillipsGarcia (@EcoEvoGal) <a href="https://twitter.com/EcoEvoGal/status/1082485924284358658?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


Twitter thread with many resources: 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Does anyone know a good resource for teaching an intro to RStudio?<br>- slides with most imp shortcuts including screenshots<br>- best practices (I know opinionated) - maybe an explanation that R!=RStudio?<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Patrick Schratz (@pjs_228) <a href="https://twitter.com/pjs_228/status/1180369562090520576?ref_src=twsrc%5Etfw">October 5, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 



## Other topics

[ECONOMY, SOCIETY, AND PUBLIC POLICY](https://econw19.classes.andrewheiss.com/) (MPA 612, BYU)


-30-
